/** Nhân viên */
export const employee = {
  "noViewPermission": "Bạn không có quyền xem module Nhân viên.",
  "listLoadErrorTitle": "Không tải được danh sách nhân viên",
  "listLoadErrorHint": "Kiểm tra kết nối Supabase, đăng nhập, migration FK (var_nhan_vien) và RPC get_nhan_vien_page. Thử tải lại.",
  "title": "Nhân viên",
  "tabList": "Danh sách",
  "tabStats": "Thống kê",
  "statsTotal": "Tổng nhân viên",
  "statsByDepartment": "Theo phòng ban",
  "statsByPosition": "Theo chức vụ",
  "statsByStatus": "Theo trạng thái",
  "statsStatusActive": "Đang hoạt động",
  "statsStatusLocked": "Đã khóa",
  "name": "Họ tên",
  "code": "Mã NV",
  "email": "Email",
  "phone": "Điện thoại",
  "gender": "Giới tính",
  "hireDate": "Ngày vào làm",
  "position": "Chức vụ",
  "department": "Phòng ban",
  "level": "Cấp bậc",
  "status": "Trạng thái",
  "birthDate": "Ngày sinh",
  "contractType": "Loại HĐ",
  "workplace": "Nơi làm việc",
  "province": "Tỉnh/TP",
  "education": "Trình độ",
  "idCard": "CCCD",
  "createdAt": "Ngày tạo",
  "positionDepartment": "Chức vụ / Phòng ban",
  "rowActions": {
    "more": "Thao tác khác",
    "popupBlocked": "Không mở được tab mới",
    "popupBlockedHint": "Trình duyệt có thể đã chặn cửa sổ mới. Cho phép popup cho trang này hoặc mở đường dẫn hồ sơ trong tab hiện tại.",
    "noPhone": "Chưa có số điện thoại",
  },
  "unassigned": "Chưa gán",
  "deleteConfirmTitle": "Xóa nhân viên?",
  "deleteConfirmMessage": "Bạn có chắc muốn xóa nhân viên",
  "deleteConfirmNote": "Bạn có thể hoàn tác trong vài giây.",
  "statusChangeTitle": "Cập nhật trạng thái",
  "statusChangeMessage": "Chọn trạng thái mới cho nhân viên",
  "bulkDeleteTitle": "Xóa nhiều nhân viên",
  "bulkDeleteMessage": "Bạn đang chọn xóa {{count}} hồ sơ nhân sự. Bạn có thể hoàn tác trong vài giây.",
  "bulkStatusTitle": "Cập nhật trạng thái hàng loạt",
  "bulkStatusMessage": "Chuyển trạng thái {{count}} nhân viên sang",
  "importSuccess": "Import {{count}} nhân viên thành công",
  "importTemplateName": "Mau_Import_Nhan_Vien",
  "exportFileName": "Danh_Sach_Nhan_Vien",
  "statusActive": "Hoạt động",
  "statusLocked": "Khóa",
  "statusProbation": "Thử việc",
  "statusLeave": "Nghỉ phép",
  "statusResigned": "Đã nghỉ việc",
  "statusActiveShort": "Đang hoạt động",
  "statusInactiveShort": "Ngưng hoạt động",
  "genderMale": "Nam",
  "genderFemale": "Nữ",
  "genderOther": "Khác",
  "maritalSingle": "Độc thân",
  "maritalMarried": "Đã kết hôn",
  "maritalDivorced": "Ly hôn",
  "maritalWidowed": "Góa",
  "eduHighSchool": "THPT",
  "eduCollege": "Trung cấp",
  "eduAssociate": "Cao đẳng",
  "eduBachelor": "Đại học",
  "eduMaster": "Thạc sĩ",
  "eduDoctor": "Tiến sĩ",
  "contractProbation": "Thử việc",
  "contractFixed": "Có thời hạn",
  "contractIndefinite": "Không thời hạn",
  "contractSeasonal": "Thời vụ",
  "relFather": "Cha",
  "relMother": "Mẹ",
  "relWife": "Vợ",
  "relHusband": "Chồng",
  "relSibling": "Anh/Chị/Em",
  "relOther": "Khác",
  "form": {
    "editTitle": "Chỉnh sửa Hồ sơ",
    "createTitle": "Thêm Nhân viên mới",
    "editSubtitle": "ID:",
    "createSubtitle": "Thiết lập thông tin nhân sự mới vào hệ thống",
    "validationError": "Vui lòng điền đầy đủ các trường bắt buộc (*) và kiểm tra lỗi bên dưới.",
    "personalInfo": "Thông tin cá nhân",
    "avatar": "Ảnh đại diện",
    "avatarPlaceholder": "Ảnh 3x4",
    "avatarHint": "PNG, JPG · Tối đa 2MB",
    "username": "Tên tài khoản",
    "usernamePlaceholder": "vd: nguyenvana",
    "authEmailHint": "Email Auth: {{email}} · Mật khẩu mặc định: 123456",
    "authEmailHintEmpty": "Email Auth sẽ là <ten_tai_khoan>@gmail.com · Mật khẩu mặc định: 123456",
    "statusSwitchActiveHint": "Tài khoản đang được phép đăng nhập.",
    "statusSwitchLockedHint": "Tài khoản bị khoá, không đăng nhập được.",
    "identity": "Định danh",
    "unit": "Bộ phận",
    "unitPlaceholder": "Chọn bộ phận...",
    "fullName": "Họ và tên",
    "fullNamePlaceholder": "Nguyễn Văn A",
    "gender": "Giới tính",
    "employeeCode": "Mã nhân viên",
    "employeeCodePlaceholder": "NV001",
    "birthDate": "Ngày sinh",
    "idCard": "CMND/CCCD",
    "idCardPlaceholder": "079095012345",
    "idIssueDate": "Ngày cấp CCCD",
    "idIssuePlace": "Nơi cấp",
    "idIssuePlaceholder": "Cục CS QLHC về TTXH",
    "nationality": "Quốc tịch",
    "nationalityPlaceholder": "Việt Nam",
    "ethnicity": "Dân tộc",
    "ethnicityPlaceholder": "Kinh",
    "religion": "Tôn giáo",
    "religionPlaceholder": "Không",
    "workInfo": "Thông tin công việc",
    "additionalSectionsSummary": "Thông tin bổ sung (liên hệ, địa chỉ, gia đình, học vấn, tài chính, bảo hiểm)",
    "stepNext": "Tiếp theo",
    "stepCoreLabel": "Cốt lõi",
    "stepCoreDesc": "Cá nhân và công việc",
    "stepContactLabel": "Liên hệ & gia đình",
    "stepContactDesc": "Liên hệ, địa chỉ, người thân",
    "stepExtraLabel": "Học vấn & pháp lý",
    "stepExtraDesc": "Học vấn, ngân hàng, bảo hiểm",
    "position": "Chức vụ",
    "positionPlaceholder": "Chọn chức vụ...",
    "donViXaPhuong": "Xã/phường (đơn vị)",
    "donViXaPhuongPlaceholder": "Chọn xã/phường trong danh mục Tỉnh thành — Xã phường…",
    "donViXaPhuongSearch": "Tìm xã, phường, tỉnh…",
    "department": "Phòng ban",
    "departmentPlaceholder": "Chọn phòng ban...",
    "level": "Cấp bậc",
    "levelPlaceholder": "Chọn cấp bậc...",
    "branch": "Chi nhánh làm việc",
    "branchPlaceholder": "Chọn chi nhánh...",
    "hireDate": "Ngày vào làm",
    "contractType": "Loại hợp đồng",
    "contractTypePlaceholder": "Chọn loại hợp đồng...",
    "contractEndDate": "Ngày hết hạn HĐ",
    "workplace": "Nơi làm việc",
    "workplacePlaceholder": "Trụ sở chính - TP.HCM",
    "workStatus": "Trạng thái làm việc",
    "workStatusPlaceholder": "Chọn trạng thái...",
    "contactInfo": "Thông tin liên hệ",
    "workEmail": "Email công việc",
    "workEmailPlaceholder": "example@company.com",
    "personalEmail": "Email cá nhân",
    "personalEmailPlaceholder": "example@gmail.com",
    "phoneNumber": "Số điện thoại",
    "phonePlaceholder": "090...",
    "emergencyContact": "Người liên hệ khẩn cấp",
    "emergencyContactPlaceholder": "Nguyễn Thị B",
    "emergencyPhone": "SĐT khẩn cấp",
    "relationship": "Quan hệ",
    "relationshipPlaceholder": "Chọn quan hệ...",
    "address": "Địa chỉ",
    "province": "Tỉnh/Thành phố",
    "provincePlaceholder": "TP. Hồ Chí Minh",
    "district": "Quận/Huyện",
    "districtPlaceholder": "Quận 1",
    "ward": "Phường/Xã",
    "wardPlaceholder": "Phường Bến Nghé",
    "detailAddress": "Địa chỉ chi tiết",
    "detailAddressPlaceholder": "Số nhà, đường, tổ/ấp...",
    "tempAddress": "Địa chỉ tạm trú",
    "tempAddressPlaceholder": "Địa chỉ tạm trú (nếu khác thường trú)...",
    "familyInfo": "Hôn nhân & Gia đình",
    "maritalStatus": "Tình trạng hôn nhân",
    "maritalPlaceholder": "Chọn...",
    "dependents": "Số người phụ thuộc",
    "dependentsPlaceholder": "0",
    "educationInfo": "Học vấn & Chứng chỉ",
    "educationLevel": "Trình độ học vấn",
    "educationPlaceholder": "Chọn trình độ...",
    "major": "Chuyên ngành",
    "majorPlaceholder": "Công nghệ thông tin",
    "school": "Trường đào tạo",
    "schoolPlaceholder": "Đại học Bách Khoa TP.HCM",
    "graduationYear": "Năm tốt nghiệp",
    "graduationYearPlaceholder": "2020",
    "certificates": "Chứng chỉ bổ sung",
    "certificatesPlaceholder": "AWS, PMP, IELTS...",
    "financialInfo": "Tài chính & Ngân hàng",
    "bankAccount": "Số tài khoản",
    "bankAccountPlaceholder": "0123456789",
    "bankName": "Tên ngân hàng",
    "bankNamePlaceholder": "Vietcombank",
    "bankBranch": "Chi nhánh",
    "bankBranchPlaceholder": "Chi nhánh Sở Giao Dịch",
    "taxId": "Mã số thuế cá nhân",
    "taxIdPlaceholder": "8012345678",
    "insuranceInfo": "Bảo hiểm",
    "socialInsurance": "Số BHXH",
    "socialInsurancePlaceholder": "7901234567",
    "healthInsurance": "Số BHYT",
    "healthInsurancePlaceholder": "HS4012345678901",
    "insuranceDate": "Ngày tham gia BH",
    "medicalFacility": "Nơi đăng ký KCB",
    "medicalFacilityPlaceholder": "Bệnh viện Đại học Y Dược"
  },
  "detail": {
    "title": "Hồ sơ nhân viên",
    "subtitle": "Mã NV:",
    "identity": "Thông tin định danh",
    "changeStatus": "Đổi trạng thái",
    "print": "In hồ sơ",
    "changePassword": "Đổi MK",
    "sendEmail": "Gửi Email",
    "callPhone": "Gọi điện",
    "permission": "Phân quyền",
    "personalInfo": "Thông tin cá nhân",
    "fullName": "Họ tên",
    "birthDate": "Ngày sinh",
    "gender": "Giới tính",
    "idCard": "CMND/CCCD",
    "idIssueDate": "Ngày cấp",
    "idIssuePlace": "Nơi cấp",
    "nationality": "Quốc tịch",
    "ethnicity": "Dân tộc",
    "religion": "Tôn giáo",
    "workInfo": "Thông tin công việc",
    "employeeCode": "Mã nhân viên",
    "position": "Chức vụ",
    "department": "Phòng ban",
    "branch": "Chi nhánh làm việc",
    "level": "Cấp bậc",
    "hireDate": "Ngày vào làm",
    "tenure": "Thâm niên",
    "contractType": "Loại hợp đồng",
    "contractEndDate": "Ngày hết hạn HĐ",
    "workplace": "Nơi làm việc",
    "contactInfo": "Thông tin liên hệ",
    "workEmail": "Email công việc",
    "personalEmail": "Email cá nhân",
    "phone": "Điện thoại",
    "emergencyContact": "Người liên hệ khẩn cấp",
    "emergencyPhone": "SĐT khẩn cấp",
    "relationship": "Quan hệ",
    "address": "Địa chỉ",
    "province": "Tỉnh/Thành phố",
    "district": "Quận/Huyện",
    "ward": "Phường/Xã",
    "detailAddress": "Địa chỉ chi tiết",
    "tempAddress": "Địa chỉ tạm trú",
    "familyInfo": "Hôn nhân & Gia đình",
    "maritalStatus": "Tình trạng hôn nhân",
    "dependents": "Số người phụ thuộc",
    "educationInfo": "Học vấn & Chứng chỉ",
    "educationLevel": "Trình độ học vấn",
    "major": "Chuyên ngành",
    "school": "Trường đào tạo",
    "graduationYear": "Năm tốt nghiệp",
    "certificates": "Chứng chỉ bổ sung",
    "financialInfo": "Tài chính & Ngân hàng",
    "bankAccount": "Số tài khoản",
    "bankName": "Ngân hàng",
    "bankBranch": "Chi nhánh",
    "taxId": "Mã số thuế cá nhân",
    "insuranceInfo": "Bảo hiểm",
    "socialInsurance": "Số BHXH",
    "healthInsurance": "Số BHYT",
    "insuranceDate": "Ngày tham gia BH",
    "medicalFacility": "Nơi đăng ký KCB",
    "systemInfo": "Thông tin hệ thống",
    "createdDate": "Ngày tạo",
    "createdBy": "Người tạo",
    "lastUpdated": "Cập nhật lần cuối",
    "updatedBy": "Người cập nhật"
  },
  "bulk": {
    "title": "Chỉnh sửa hàng loạt",
    "subtitle": "nhân viên được chọn",
    "applyButton": "Áp dụng cho {{count}} nhân viên",
    "selectedLabel": "Nhân viên được chọn:",
    "warning": "Chỉ các trường được đánh dấu tick mới được cập nhật. Các trường khác giữ nguyên giá trị hiện tại.",
    "workSection": "Phân bổ công việc",
    "changeDepartment": "Thay đổi Phòng ban",
    "changeBranch": "Thay đổi Chi nhánh làm việc",
    "changePosition": "Thay đổi Chức vụ",
    "changeLevel": "Thay đổi Cấp bậc",
    "contractSection": "Hợp đồng & Trạng thái",
    "changeContract": "Thay đổi Loại hợp đồng",
    "changeStatus": "Thay đổi Trạng thái"
  },
  "toolbar": {
    "department": "Phòng ban",
    "position": "Chức vụ",
    "status": "Trạng thái",
    "bulkEdit": "Chỉnh sửa hàng loạt",
    "editCount": "Sửa {{count}}",
    "bulkEditDesc": "Cập nhật {{count}} nhân viên đã chọn",
    "importDesc": "Nhập nhân viên từ file Excel",
    "exportDesc": "Xuất danh sách ra file Excel",
    "importData": "Nhập dữ liệu",
    "exportData": "Xuất dữ liệu"
  },
  "stats": {
    "department": "Phòng ban",
    "status": "Trạng thái",
    "exportReport": "Xuất báo cáo",
    "loading": "Đang tải thống kê...",
    "exporting": "Đang xuất...",
    "selectFormat": "Chọn định dạng",
    "dataAndMeta": "Số liệu + metadata",
    "printReport": "Báo cáo in",
    "kpiOptions": "Tùy chọn KPI",
    "showKpi": "Hiển thị KPI",
    "totalEmployees": "Tổng nhân viên",
    "working": "Đang làm việc",
    "probation": "Thử việc",
    "leaveResigned": "Nghỉ việc / phép",
    "noData": "Không có dữ liệu",
    "noDataHint": "Thử bỏ bớt bộ lọc hoặc đổi khoảng thời gian để xem kết quả.",
    "noEmployeeInPeriod": "Chưa có nhân viên trong khoảng thời gian này.",
    "clearFilters": "Xóa bộ lọc",
    "comparedLastMonth": "So với tháng trước",
    "newHiresInPeriod": "Tuyển mới trong kỳ:",
    "genderRatio": "Nam/Nữ:",
    "largestDepartment": "Phòng ban lớn nhất:",
    "comparedLastYear": "So với cùng kỳ năm trước: Tổng",
    "workingShort": "Hoạt động",
    "lockedShort": "Khóa",
    "positionChart": "Phân bổ theo chức vụ",
    "newAccountsInPeriod": "Tài khoản mới trong kỳ:",
    "accountTrendChart": "Xu hướng tạo tài khoản (12 tháng)",
    "newAccounts": "Tài khoản mới",
    "chartDrillDownHint": "Chạm hoặc nhấn vào biểu đồ để mở danh sách nhân viên (theo phòng ban hoặc trạng thái).",
    "departmentChart": "Phân bổ theo phòng ban",
    "statusChart": "Trạng thái nhân sự",
    "quantity": "Số lượng",
    "trendChart": "Xu hướng tuyển dụng (12 tháng)",
    "newHires": "Tuyển mới",
    "genderChart": "Tỷ lệ giới tính",
    "departmentTable": "Thống kê theo phòng ban",
    "total": "Tổng",
    "leave": "Nghỉ",
    "activeRate": "Tỷ lệ HĐ",
    "exportSuccess": "Xuất báo cáo Excel thành công",
    "exportSuccessDesc": "Báo cáo đã được tải về.",
    "exportError": "Xuất báo cáo thất bại",
    "dateRange": {
      "week": "Tuần",
      "month": "Tháng",
      "quarter": "Quý",
      "year": "Năm",
      "custom": "Tùy chọn"
    },
    "preset": {
      "all": "Tất cả",
      "thisWeek": "Tuần này",
      "lastWeek": "Tuần trước",
      "thisMonth": "Tháng này",
      "lastMonth": "Tháng trước",
      "thisQuarter": "Quý này",
      "lastQuarter": "Quý trước",
      "thisYear": "Năm nay",
      "custom": "Tùy chọn"
    }
  },
  "validation": {
    "usernameMin": "Tên tài khoản phải có ít nhất 2 ký tự",
    "usernameFormat": "Tên tài khoản chỉ chứa chữ, số, dấu chấm, gạch dưới hoặc gạch ngang",
    "fullNameMin": "Họ tên phải có ít nhất 2 ký tự",
    "codeRequired": "Mã nhân viên là bắt buộc",
    "nameMin": "Họ tên phải có ít nhất 2 ký tự",
    "emailInvalid": "Địa chỉ email không hợp lệ",
    "phoneRequired": "Số điện thoại là bắt buộc",
    "phoneInvalid": "SĐT không hợp lệ (VD: 0901234567)",
    "positionRequired": "Vui lòng chọn chức vụ",
    "departmentRequired": "Vui lòng chọn phòng ban",
    "unitRequired": "Vui lòng chọn bộ phận",
    "branchRequired": "Vui lòng chọn ít nhất một chi nhánh",
    "donViRequired": "Chức vụ cấp \"Xã phường\" bắt buộc chọn xã/phường (đơn vị)",
    "hireDateInvalid": "Ngày vào làm không hợp lệ",
    "ageMin": "Nhân viên phải đủ 16 tuổi trở lên",
    "idCardLength": "CCCD phải có đúng 12 chữ số",
    "personalEmailInvalid": "Email cá nhân không hợp lệ",
    "emergencyPhoneInvalid": "SĐT khẩn cấp không hợp lệ",
    "taxIdLength": "Mã số thuế phải có 10 hoặc 13 chữ số",
    "contractEndRequired": "Hợp đồng có thời hạn phải có ngày hết hạn"
  },
  "toast": {
    "createSuccess": "Thêm nhân viên thành công",
    "updateSuccess": "Cập nhật thông tin thành công",
    "statusUpdateSuccess": "Đã cập nhật trạng thái {{count}} nhân viên",
    "bulkUpdateSuccess": "Đã cập nhật {{count}} nhân viên",
    "deleteSuccess": "Đã xóa thành công {{count}} nhân viên",
    "deleteCount": "Đã xóa {{count}} nhân viên",
    "undo": "Hoàn tác",
    "undoSuccess": "Đã hoàn tác xóa",
    "authCreated": "Đã tạo tài khoản đăng nhập",
    "authPasswordReset": "Đã đặt lại mật khẩu về 123456",
    "authDeleted": "Đã xóa tài khoản đăng nhập cũ"
  },
  "authConflict": {
    "title": "Tài khoản đăng nhập đã tồn tại",
    "desc": "Email {{email}} đã có sẵn trên hệ thống. Bạn muốn xử lý thế nào?",
    "optionResetTitle": "Đặt lại mật khẩu về 123456",
    "optionResetDesc": "Mật khẩu hiện tại sẽ bị ghi đè bằng 123456 và liên kết với hồ sơ nhân viên này.",
    "optionKeepTitle": "Giữ mật khẩu hiện tại",
    "optionKeepDesc": "Không thay đổi mật khẩu; chỉ liên kết tài khoản Auth có sẵn với hồ sơ nhân viên này."
  },
  "service": {
    "notFound": "Nhân viên không tồn tại"
  },
  "pdf": {
    "title": "HỒ SƠ NHÂN SỰ",
    "code": "Ma NV:",
    "personalInfo": "THÔNG TIN CÁ NHÂN",
    "workInfo": "THÔNG TIN CÔNG VIỆC",
    "contactInfo": "THÔNG TIN LIÊN HỆ",
    "address": "ĐỊA CHỈ",
    "familyInfo": "HÔN NHÂN & GIA ĐÌNH",
    "educationInfo": "HỌC VẤN & CHỨNG CHỈ",
    "financialInfo": "TÀI CHÍNH & NGÂN HÀNG",
    "insuranceInfo": "BẢO HIỂM",
    "printedAt": "In lúc:"
  },
  "profile": {
    "notFound": "Không tìm thấy hồ sơ nhân viên.",
    "loadError": "Lỗi tải hồ sơ nhân viên.",
    "downloadPdf": "Tải PDF",
    "print": "In",
    "download": "Tải"
  },
  "export": {
    "doc": "Word (.doc)",
    "docx": "Word (.docx)",
    "excel": "Excel (.xlsx)",
    "pdf": "PDF"
  },
  "report": {
    "title": "Báo cáo thống kê nhân sự",
    "period": "Khoảng thời gian",
    "departmentFilter": "Bộ lọc phòng ban",
    "statusFilter": "Bộ lọc trạng thái",
    "allFilter": "Tất cả",
    "exportDate": "Ngày xuất",
    "indicator": "Chỉ số",
    "value": "Giá trị",
    "ratio": "Tỷ lệ",
    "overviewSheet": "Tổng quan",
    "byDepartmentSheet": "Theo phòng ban",
    "pdfTitle": "BÁO CÁO THỐNG KÊ NHÂN SỰ",
    "pdfPeriod": "Khoảng thời gian:",
    "pdfExportDate": "Xuất ngày:",
    "pdfDepartment": "Phòng ban:",
    "pdfStatus": "Trạng thái:",
    "pdfByDepartment": "Thống kê theo phòng ban",
    "activeRatePercent": "Tỷ lệ HĐ (%)"
  },
  "store": {
    "usernameCol": "Tên tài khoản",
    "unitCol": "Bộ phận",
    "codeCol": "Mã NV",
    "nameCol": "Họ và tên",
    "positionDeptCol": "Chức vụ / Phòng ban",
    "positionCol": "Chức vụ",
    "emailCol": "Email",
    "phoneCol": "SĐT",
    "hireDateCol": "Ngày vào",
    "genderCol": "Giới tính",
    "statusCol": "Trạng thái",
    "birthDateCol": "Ngày sinh",
    "departmentCol": "Phòng ban",
    "donViCol": "Đơn vị",
    "levelCol": "Cấp bậc",
    "contractCol": "Loại HĐ",
    "branchCol": "Chi nhánh",
    "workplaceCol": "Nơi làm việc",
    "provinceCol": "Tỉnh/TP",
    "educationCol": "Trình độ",
    "idCardCol": "CCCD",
    "createdCol": "Ngày tạo"
  }
} as const;
