/** Danh mục nguyên liệu */
export const materialCategory = {
  exportName: 'Tên danh mục',
  exportCode: 'Mã danh mục',
  exportLevel: 'Cấp độ',
  exportOrder: 'Thứ tự',
  exportStatus: 'Trạng thái',
  exportParent: 'Danh mục cha',
  noExportData: 'Không có dữ liệu để xuất',
  toolbar: {
    rootCategory: 'Danh mục gốc',
  },
  footerRecords: 'bản ghi',
  title: 'Danh mục nguyên liệu',
  noViewPermission: 'Bạn không có quyền xem module Danh mục nguyên liệu.',
  pageTitle: 'Danh mục nguyên liệu',
  pageDescription: 'Phân loại nhóm nguyên liệu (tối đa 2 cấp).',
  addButton: 'Thêm danh mục',
  deleteTitle: 'Xóa danh mục',
  deleteMessage:
    'Bạn có chắc chắn muốn xóa danh mục này? Không thể xóa nếu đang có danh mục con.',
  loading: 'Đang tải danh mục nguyên liệu...',
  empty: 'Chưa có danh mục nào',
  emptyHint: 'Hãy tạo danh mục gốc (Vải, Chỉ, Phụ liệu, …) để bắt đầu.',
  listLoadErrorTitle: 'Không tải được danh sách danh mục',
  listLoadErrorHint:
    'Kiểm tra kết nối Supabase, đăng nhập và migration sx_danh_muc_nguyen_lieu. Thử tải lại.',
  name: 'Tên danh mục',
  code: 'Mã danh mục',
  level: 'Cấp độ',
  levelBadge: 'Cấp {{level}}',
  active: 'Hoạt động',
  inactive: 'Ngừng',
  form: {
    editTitle: 'Chỉnh sửa danh mục',
    createTitle: 'Thêm danh mục mới',
    namePlaceholder: 'VD: Vải cotton, Chỉ polyester',
    codePlaceholder: 'VD: VAI, CHI (tùy chọn)',
    parentNone: '-- Không (Danh mục gốc) --',
    parentHint: 'Chỉ chọn danh mục cấp 1 làm cha.',
    descriptionPlaceholder: 'Mô tả ngắn về danh mục...',
  },
  validation: {
    nameMin: 'Tên danh mục phải có ít nhất 2 ký tự',
    nameMax: 'Tên danh mục quá dài',
    codeMax: 'Mã danh mục tối đa 50 ký tự',
    statusInvalid: 'Trạng thái không hợp lệ',
    sortOrderMin: 'Thứ tự phải lớn hơn hoặc bằng 0',
  },
  toast: {
    createSuccess: 'Tạo danh mục thành công',
    updateSuccess: 'Cập nhật thành công',
    deleteSuccess: 'Xóa danh mục thành công',
    importSuccess: 'Đã import {{count}} danh mục',
  },
  importTemplateName: 'Mau_Import_Danh_Muc_Nguyen_Lieu',
  import: {
    parentMissing: 'Dòng {{row}}: Danh mục cha không tồn tại',
    parentNotRoot: 'Dòng {{row}}: Cha phải là danh mục cấp 1',
  },
  service: {
    notFound: 'Danh mục không tồn tại',
    hasChildren: 'Không thể xóa danh mục đang có danh mục con.',
    parentNotFound: 'Danh mục cha không tồn tại',
    parentNotRoot: 'Chỉ được chọn danh mục cấp 1 làm cha.',
    level2ParentLocked: 'Danh mục cấp 2 không thể đổi danh mục cha.',
    maxLevel: 'Chỉ cho phép tối đa 2 cấp danh mục.',
  },
  detail: {
    title: 'Chi tiết danh mục',
    activate: 'Kích hoạt',
    deactivate: 'Ngưng',
    level: 'Cấp độ',
    order: 'Thứ tự',
    parent: 'Danh mục cha',
    noParent: '— Danh mục gốc —',
    updated: 'Cập nhật',
    createdAt: 'Được tạo lúc',
    basicInfo: 'Thông tin cơ bản',
    systemInfo: 'Thông tin hệ thống',
    description: 'Mô tả',
    childrenSection: 'Danh mục con',
    addChild: 'Thêm con',
    noChildren: 'Chưa có danh mục con',
    noChildrenHint: 'Bấm Thêm để tạo danh mục cấp 2 trực tiếp.',
  },
  store: {
    orderCol: 'Thứ tự',
    nameCol: 'Tên danh mục',
    codeCol: 'Mã',
    descCol: 'Mô tả',
    levelCol: 'Cấp',
    statusCol: 'Trạng thái',
    parentCol: 'Danh mục cha',
    updatedCol: 'Cập nhật',
  },
  statusChangeTitle: 'Chuyển trạng thái danh mục',
  statusChangeMessage: 'Chuyển "{{name}}" sang trạng thái {{status}}?',
} as const;
