/** Chi nhánh */
export const branch = {
  noViewPermission: 'Bạn không có quyền xem module Chi nhánh.',
  title: 'Chi nhánh',
  deleteTitle: 'Xóa chi nhánh',
  deleteMessage: 'Bạn có chắc chắn muốn xóa chi nhánh này không?',
  bulkDeleteTitle: 'Xóa nhiều chi nhánh',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} chi nhánh đã chọn?',
  statusChangeTitle: 'Chuyển trạng thái chi nhánh',
  statusChangeMessage: 'Bạn có muốn chuyển trạng thái {{count}} chi nhánh sang',
  noExportData: 'Không có dữ liệu để xuất',
  exportName: 'Tên chi nhánh',
  exportCode: 'Mã chi nhánh',
  exportAddress: 'Địa chỉ',
  exportPhone: 'Điện thoại',
  exportEmail: 'Email',
  exportDesc: 'Mô tả',
  exportStatus: 'Trạng thái',
  importTemplateName: 'Mau_Import_Chi_Nhanh',
  active: 'Hoạt động',
  inactive: 'Ngừng',
  loading: 'Đang tải danh sách chi nhánh...',
  empty: 'Chưa có chi nhánh nào',
  emptyHint: 'Hãy tạo chi nhánh đầu tiên để gán cho nhân viên.',
  listLoadErrorTitle: 'Không tải được danh sách chi nhánh',
  listLoadErrorHint: 'Kiểm tra kết nối Supabase, đăng nhập (RLS yêu cầu authenticated) và migration var_chi_nhanh. Thử tải lại.',
  footerRecords: 'chi nhánh',
  form: {
    editTitle: 'Chỉnh sửa Chi nhánh',
    createTitle: 'Thêm Chi nhánh mới',
    editSubtitle: 'Cập nhật thông tin chi nhánh hiện có',
    createSubtitle: 'Khai báo đơn vị / điểm làm việc mới',
    generalInfo: 'Thông tin chung',
    contactInfo: 'Liên hệ',
    name: 'Tên chi nhánh',
    namePlaceholder: 'VD: Chi nhánh TP. Hồ Chí Minh',
    code: 'Mã chi nhánh',
    codePlaceholder: 'VD: HCM-01',
    address: 'Địa chỉ',
    addressPlaceholder: 'Số nhà, đường, quận/huyện, tỉnh/thành',
    phone: 'Điện thoại',
    phonePlaceholder: 'VD: 028 1234 5678',
    email: 'Email',
    emailPlaceholder: 'VD: hcm@congty.vn',
    description: 'Mô tả',
    descriptionPlaceholder: 'Ghi chú thêm về chi nhánh...',
    status: 'Trạng thái',
    order: 'Thứ tự hiển thị',
    validationError: 'Vui lòng kiểm tra các trường bắt buộc và thử lại.',
  },
  store: {
    orderCol: 'Thứ tự',
    nameCol: 'Tên chi nhánh',
    codeCol: 'Mã',
    addressCol: 'Địa chỉ',
    phoneCol: 'Điện thoại',
    emailCol: 'Email',
    descCol: 'Mô tả',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật cuối',
  },
  validation: {
    nameMin: 'Tên chi nhánh phải có ít nhất 3 ký tự',
    nameMax: 'Tên chi nhánh quá dài',
    codeMax: 'Mã chi nhánh tối đa 50 ký tự',
    codeFormat: 'Mã chỉ chứa chữ hoa, số, gạch ngang và gạch dưới (VD: HCM-01)',
    addressMax: 'Địa chỉ tối đa 500 ký tự',
    phoneMax: 'Số điện thoại tối đa 50 ký tự',
    emailMax: 'Email tối đa 255 ký tự',
    descMax: 'Mô tả tối đa 500 ký tự',
    statusInvalid: 'Trạng thái không hợp lệ',
  },
  toast: {
    createSuccess: 'Tạo chi nhánh thành công',
    updateSuccess: 'Cập nhật thành công',
    statusUpdate: 'Đã cập nhật trạng thái {{count}} bản ghi',
    deleteSuccess: 'Đã xóa thành công {{count}} chi nhánh',
    importSuccess: 'Đã nhập {{count}} chi nhánh',
  },
  service: {
    notFound: 'Chi nhánh không tồn tại',
    duplicateName: 'Tên chi nhánh đã tồn tại',
    duplicateCode: 'Mã chi nhánh đã tồn tại',
    hasEmployees: 'Không thể xóa chi nhánh đang có nhân viên gán',
  },
  detail: {
    title: 'Chi tiết chi nhánh',
    subtitle: 'Mã chi nhánh',
    activate: 'Kích hoạt',
    deactivate: 'Ngưng',
    basicInfo: 'Thông tin cơ bản',
    contactInfo: 'Liên hệ',
    systemInfo: 'Thông tin hệ thống',
    order: 'Thứ tự hiển thị',
    updated: 'Cập nhật',
    createdAt: 'Được tạo lúc',
  },
} as const;
