/** Thuộc tính hàng hóa */
export const productAttribute = {
  noViewPermission: 'Bạn không có quyền xem module Thuộc tính hàng hóa.',
  title: 'Thuộc tính hàng hóa',
  deleteTitle: 'Xóa thuộc tính',
  deleteMessage: 'Bạn có chắc chắn muốn xóa thuộc tính này không?',
  bulkDeleteTitle: 'Xóa nhiều thuộc tính',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} thuộc tính đã chọn?',
  statusChangeTitle: 'Chuyển trạng thái thuộc tính',
  statusChangeMessage: 'Bạn có muốn chuyển trạng thái {{count}} thuộc tính sang',
  noExportData: 'Không có dữ liệu để xuất',
  exportDisplayName: 'Tên hiển thị',
  exportValues: 'Các giá trị',
  exportStatus: 'Trạng thái',
  importTemplateName: 'Mau_Import_Thuoc_Tinh_Hang_Hoa',
  active: 'Hoạt động',
  inactive: 'Ngừng',
  loading: 'Đang tải danh sách thuộc tính...',
  empty: 'Chưa có thuộc tính nào',
  emptyHint: 'Hãy tạo thuộc tính đầu tiên cho hàng hóa.',
  listLoadErrorTitle: 'Không tải được danh sách thuộc tính',
  listLoadErrorHint:
    'Kiểm tra kết nối Supabase, đăng nhập (RLS) và migration sx_thuoc_tinh_hang_hoa. Thử tải lại.',
  form: {
    editTitle: 'Chỉnh sửa Thuộc tính',
    createTitle: 'Thêm Thuộc tính mới',
    editSubtitle: 'Cập nhật thuộc tính hiện có',
    createSubtitle: 'Khai báo thuộc tính mở rộng cho hàng hóa',
    generalInfo: 'Thông tin thuộc tính',
    displayName: 'Tên hiển thị',
    displayNamePlaceholder: 'VD: Mã vải, Số đo - Ngực',
    valuesLabel: 'Các giá trị',
    valuesPlaceholder: 'Nhập giá trị và nhấn Thêm hoặc Enter',
    valuesEmpty: 'Chưa có giá trị nào — thêm giá trị để người dùng chọn khi nhập liệu.',
    addValue: 'Thêm',
    removeValue: 'Xóa {{value}}',
    status: 'Trạng thái',
    validationError: 'Vui lòng kiểm tra các trường bắt buộc và thử lại.',
  },
  detail: {
    title: 'Chi tiết Thuộc tính',
    subtitle: 'Thông tin thuộc tính hàng hóa',
    basicInfo: 'Thông tin cơ bản',
    systemInfo: 'Hệ thống',
    createdAt: 'Ngày tạo',
    updated: 'Cập nhật',
    activate: 'Kích hoạt',
    deactivate: 'Ngừng hoạt động',
  },
  store: {
    orderCol: 'TT',
    displayNameCol: 'Tên hiển thị',
    valuesCol: 'Các giá trị',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật cuối',
  },
  table: {
    moreValues: '+{{count}}',
  },
  validation: {
    displayNameRequired: 'Vui lòng nhập tên hiển thị',
    displayNameMax: 'Tên hiển thị quá dài',
    orderMin: 'Thứ tự phải lớn hơn hoặc bằng 0',
    statusInvalid: 'Trạng thái không hợp lệ',
    valueEmpty: 'Giá trị không được để trống',
  },
  toast: {
    createSuccess: 'Tạo thuộc tính thành công',
    updateSuccess: 'Cập nhật thành công',
    statusUpdate: 'Đã cập nhật trạng thái {{count}} bản ghi',
    deleteSuccess: 'Đã xóa thành công {{count}} thuộc tính',
    importSuccess: 'Đã nhập {{count}} thuộc tính',
  },
  service: {
    duplicateName: 'Tên hiển thị đã tồn tại',
    notFound: 'Không tìm thấy thuộc tính',
    createFetchFailed: 'Tạo thành công nhưng không tải lại được bản ghi',
  },
};
