/** Thông tin tổ chức + thương hiệu (Mangiico ERP) */
export const company = {
  noViewPermission: 'Bạn không có quyền xem module Thông tin tổ chức.',
  title: 'Thông tin tổ chức',
  description: 'Cấu hình tên ứng dụng Mangiico ERP, logo, mô tả ngắn và thông tin liên hệ hiển thị trên hệ thống.',
  brandSection: 'Thương hiệu & Logo',
  logoUrl: 'Link logo',
  logoUrlPlaceholder: 'https://example.com/logo.png',
  logoUrlHint: 'Dán link ảnh logo (PNG, JPG, WebP, SVG). Logo hiển thị trên thanh bên và tiêu đề trình duyệt.',
  logoPreviewEmpty: 'Chưa có logo',
  logoLoadError: 'Không tải được ảnh từ link này. Kiểm tra lại URL.',
  appName: 'Tên ứng dụng',
  appNamePlaceholder: 'Ví dụ: Mangiico ERP',
  appNameHint: 'Hiển thị trên thanh bên và tiêu đề trình duyệt.',
  appDescription: 'Mô tả ngắn',
  appDescPlaceholder: 'Ví dụ: Hệ thống quản trị doanh nghiệp',
  appDescHint: 'Hiển thị dưới tên ứng dụng trên thanh bên (tối đa 30 ký tự).',
  legalSection: 'Định danh tổ chức & liên hệ',
  companyName: 'Tên tổ chức',
  companyNamePlaceholder: 'Ví dụ: Công ty TNHH Mangiico',
  phone: 'Số điện thoại',
  phonePlaceholder: '(+84) ...',
  email: 'Email liên hệ',
  emailPlaceholder: 'contact@example.com',
  website: 'Website',
  websitePlaceholder: 'www.example.com',
  address: 'Địa chỉ trụ sở',
  addressPlaceholder: 'Số nhà, đường, phường/xã…',
  saveButton: 'Lưu thông tin',
  saveSuccess: 'Cập nhật thông tin tổ chức thành công!',
  validation: {
    appNameMin: 'Tên ứng dụng quá ngắn',
    appDescMax: 'Mô tả ngắn không được quá 30 ký tự',
    companyNameMin: 'Tên tổ chức là bắt buộc',
    emailInvalid: 'Email không hợp lệ',
    logoUrlInvalid: 'Link logo không hợp lệ (cần bắt đầu bằng http:// hoặc https://)',
  },
} as const;
