/** Danh sách nguyên liệu */
export const materialCatalog = {
  noViewPermission: 'Bạn không có quyền xem module Danh sách nguyên liệu.',
  title: 'Danh sách nguyên liệu',
  deleteTitle: 'Xóa nguyên liệu',
  deleteMessage: 'Bạn có chắc chắn muốn xóa nguyên liệu này không?',
  bulkDeleteTitle: 'Xóa nhiều nguyên liệu',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} nguyên liệu đã chọn?',
  statusChangeTitle: 'Chuyển trạng thái nguyên liệu',
  statusChangeMessage: 'Bạn có muốn chuyển trạng thái {{count}} nguyên liệu sang',
  loading: 'Đang tải danh sách nguyên liệu...',
  empty: 'Chưa có nguyên liệu nào',
  emptyHint: 'Hãy tạo nguyên liệu đầu tiên và chọn danh mục cấp 2.',
  listLoadErrorTitle: 'Không tải được danh sách nguyên liệu',
  listLoadErrorHint:
    'Kiểm tra kết nối Supabase, đăng nhập và migration sx_danh_sach_nguyen_lieu. Thử tải lại.',
  form: {
    editTitle: 'Chỉnh sửa nguyên liệu',
    createTitle: 'Thêm nguyên liệu mới',
    editSubtitle: 'Cập nhật thông tin nguyên liệu',
    createSubtitle: 'Khai báo nguyên liệu thuộc danh mục cấp 2',
    generalInfo: 'Thông tin nguyên liệu',
    code: 'Mã nguyên liệu',
    codePlaceholder: 'VD: VAI-CT-001',
    name: 'Tên nguyên liệu',
    namePlaceholder: 'VD: Vải cotton trắng 40s',
    category: 'Danh mục',
    categoryPlaceholder: 'Chọn danh mục cấp 2…',
    description: 'Mô tả',
    descriptionPlaceholder: 'Mô tả ngắn…',
    status: 'Trạng thái',
    specSection: 'Thông số nguyên liệu',
    selectCategoryFirst: 'Chọn danh mục để nhập thông số.',
    unit: 'Đơn vị tính',
    unitPlaceholder: 'Chọn hoặc nhập đơn vị tính…',
    unitSearch: 'Tìm đơn vị tính…',
    unitCreate: 'Thêm « {{value}} »',
    color: 'Màu sắc',
    colorPlaceholder: 'Chọn hoặc nhập màu…',
    colorSearch: 'Tìm màu…',
    colorCreate: 'Thêm « {{value}} »',
    composition: 'Thành phần',
    compositionPlaceholder: 'Chọn hoặc nhập thành phần…',
    compositionSearch: 'Tìm thành phần…',
    compositionCreate: 'Thêm « {{value}} »',
    width: 'Khổ vải',
    widthPlaceholder: 'Chọn hoặc nhập khổ…',
    widthSearch: 'Tìm khổ vải…',
    widthCreate: 'Thêm « {{value}} »',
    gsm: 'Định lượng GSM',
    gsmPlaceholder: 'Chọn hoặc nhập GSM…',
    gsmSearch: 'Tìm GSM…',
    gsmCreate: 'Thêm « {{value}} »',
    origin: 'Xuất xứ',
    originPlaceholder: 'Chọn hoặc nhập xuất xứ…',
    originSearch: 'Tìm xuất xứ…',
    originCreate: 'Thêm « {{value}} »',
    validationError: 'Vui lòng kiểm tra các trường bắt buộc và thử lại.',
  },
  detail: {
    title: 'Chi tiết nguyên liệu',
    subtitle: 'Thông tin nguyên liệu may',
    basicInfo: 'Thông tin cơ bản',
    specSection: 'Thông số nguyên liệu',
    systemInfo: 'Hệ thống',
    categoryGroup: 'Nhóm danh mục',
    category: 'Danh mục',
    createdAt: 'Ngày tạo',
    updated: 'Cập nhật',
    activate: 'Kích hoạt',
    deactivate: 'Ngừng hoạt động',
  },
  store: {
    codeCol: 'Mã NL',
    nameCol: 'Tên nguyên liệu',
    categoryCol: 'Danh mục',
    groupCol: 'Nhóm',
    colorCol: 'Màu',
    unitCol: 'ĐVT',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật',
  },
  validation: {
    codeRequired: 'Vui lòng nhập mã nguyên liệu',
    codeMax: 'Mã nguyên liệu quá dài',
    nameRequired: 'Vui lòng nhập tên nguyên liệu',
    nameMax: 'Tên nguyên liệu quá dài',
    categoryRequired: 'Vui lòng chọn danh mục cấp 2',
    statusInvalid: 'Trạng thái không hợp lệ',
    gsmInvalid: 'Định lượng GSM phải là số dương',
  },
  toast: {
    createSuccess: 'Tạo nguyên liệu thành công',
    updateSuccess: 'Cập nhật thành công',
    statusUpdate: 'Đã cập nhật trạng thái {{count}} nguyên liệu',
    deleteSuccess: 'Đã xóa thành công {{count}} nguyên liệu',
  },
  service: {
    duplicateCode: 'Mã nguyên liệu đã tồn tại',
    notFound: 'Không tìm thấy nguyên liệu',
    createFetchFailed: 'Tạo thành công nhưng không tải lại được bản ghi',
  },
};
