export const warehouseSlip = {
  title: 'Phiếu kho',
  addButton: 'Thêm phiếu',
  tabList: 'Danh sách',
  tabLines: 'Chi tiết',
  deleteTitle: 'Xóa phiếu kho?',
  deleteMessage: 'Phiếu nháp sẽ bị xóa vĩnh viễn.',
  bulkDeleteTitle: 'Xóa nhiều phiếu kho?',
  bulkDeleteMessage: 'Xóa {count} phiếu nháp đã chọn?',
  editBlockedStatus: 'Chỉ sửa được phiếu ở trạng thái Nháp.',
  deleteBlockedStatus: 'Chỉ xóa được phiếu ở trạng thái Nháp.',
  noViewPermission: 'Bạn không có quyền xem module Phiếu kho.',
  loading: 'Đang tải phiếu kho...',
  linesLoading: 'Đang tải chi tiết phiếu...',
  empty: 'Chưa có phiếu kho',
  linesEmpty: 'Chưa có dòng chi tiết',
  emptyHint: 'Tạo phiếu nhập hoặc xuất kho để bắt đầu.',
  linesEmptyHint: 'Các dòng chi tiết phiếu kho sẽ hiển thị tại tab này.',
  listLoadErrorTitle: 'Không tải được danh sách phiếu kho',
  listLoadErrorHint: 'Kiểm tra kết nối Supabase và quyền truy cập.',
  linesLoadErrorTitle: 'Không tải được chi tiết phiếu',
  linesLoadErrorHint: 'Kiểm tra kết nối Supabase và quyền truy cập.',
  footerRecords: 'phiếu',
  footerLineRecords: 'dòng',
  filter: {
    dateAll: 'Tất cả ngày',
    dateThisMonth: 'Tháng này',
    dateLastMonth: 'Tháng trước',
    dateCustom: 'Tùy chọn',
    slipDate: 'Ngày phiếu',
  },
  store: {
    codeCol: 'Mã phiếu',
    typeCol: 'Loại',
    purposeCol: 'Mục đích',
    warehouseCol: 'Kho',
    destWarehouseCol: 'Kho đích',
    dateCol: 'Ngày phiếu',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật',
    productionOrderCol: 'Lệnh SX',
    purchaseOrderCol: 'Đơn mua',
    lineCountCol: 'Số dòng',
    itemCodeCol: 'Mã hàng',
    itemNameCol: 'Tên hàng',
    qtyCol: 'Số lượng',
    unitCol: 'ĐVT',
    itemTypeCol: 'Loại hàng',
    qtyOrderCol: 'SL theo lệnh',
    qtyReceivedCol: 'SL đã nhập',
    qtyRemainingCol: 'SL còn lại',
    qtyInputCol: 'SL nhập',
  },
  form: {
    createTitle: 'Tạo phiếu kho',
    editTitle: 'Sửa phiếu kho',
    type: 'Loại phiếu',
    purpose: 'Mục đích',
    warehouse: 'Kho',
    destWarehouse: 'Kho đích',
    slipDate: 'Ngày phiếu',
    productionOrder: 'Lệnh sản xuất',
    productionOrderPlaceholder: 'Chọn lệnh SX (tùy chọn)',
    purchaseOrder: 'Đơn mua',
    purchaseOrderPlaceholder: 'Chọn đơn mua (tùy chọn)',
    note: 'Ghi chú',
    linesSection: 'Chi tiết hàng',
    addLine: 'Thêm dòng',
    addLineHint: 'Thêm ít nhất một dòng nguyên liệu hoặc thành phẩm.',
    itemTypeMaterial: 'Nguyên liệu',
    itemTypeProduct: 'Thành phẩm',
    importFromBom: 'Lấy từ BOM lệnh SX',
    importFromPurchase: 'Lấy từ đơn mua',
    setRemainingAll: 'Đặt tất cả = còn lại',
    orderProductsHint: 'Nhập số lượng cần nhập kho cho từng sản phẩm.',
    orderProductsLoading: 'Đang tải danh sách sản phẩm...',
    orderProductsEmpty: 'Đơn hàng chưa có dòng sản phẩm.',
    qtyExceedsWarning: 'SL nhập vượt quá SL còn lại',
    saveDraft: 'Lưu nháp',
    saveComplete: 'Hoàn thành',
    validationError: 'Kiểm tra lại thông tin phiếu kho.',
  },
  detail: {
    title: 'Chi tiết phiếu kho',
    slipInfo: 'Thông tin phiếu',
    linesSection: 'Chi tiết hàng',
    noLines: 'Chưa có dòng hàng',
    systemInfo: 'Thông tin hệ thống',
    print: 'In phiếu',
    cancelSlip: 'Hủy phiếu',
  },
  print: {
    title: 'In phiếu kho',
    inboundTitle: 'PHIẾU NHẬP KHO',
    outboundTitle: 'PHIẾU XUẤT KHO',
    slipCode: 'Số phiếu',
    slipDate: 'Ngày',
    warehouse: 'Kho',
    destWarehouse: 'Kho đích',
    purpose: 'Mục đích',
    productionOrder: 'Lệnh SX',
    purchaseOrder: 'Đơn mua',
    note: 'Ghi chú',
    stt: 'STT',
    itemCode: 'Mã hàng',
    itemName: 'Tên hàng',
    unit: 'ĐVT',
    qty: 'Số lượng',
    preparedBy: 'Người lập',
    warehouseKeeper: 'Thủ kho',
    accountant: 'Kế toán',
  },
  cancelTitle: 'Hủy phiếu kho?',
  cancelMessage: 'Phiếu sẽ chuyển sang trạng thái Hủy và hoàn tồn kho nếu đã post.',
  validation: {
    purposeRequired: 'Chọn mục đích phiếu',
    warehouseRequired: 'Chọn kho',
    dateRequired: 'Chọn ngày phiếu',
    qtyPositive: 'Số lượng phải lớn hơn 0',
    materialRequired: 'Chọn nguyên liệu',
    productRequired: 'Chọn thành phẩm',
    linesRequired: 'Cần ít nhất một dòng chi tiết',
    destWarehouseRequired: 'Chọn kho đích cho phiếu chuyển kho',
  },
  toast: {
    createSuccess: 'Đã tạo phiếu kho',
    updateSuccess: 'Đã cập nhật phiếu kho',
    deleteSuccess: 'Đã xóa phiếu kho',
    cancelSuccess: 'Đã hủy phiếu kho',
    importBomSuccess: 'Đã lấy dòng từ BOM lệnh SX',
    importPurchaseSuccess: 'Đã lấy dòng từ đơn mua',
  },
  status: {
    nhap: 'Nháp',
    hoanThanh: 'Hoàn thành',
    huy: 'Hủy',
  },
  type: {
    nhap: 'Nhập',
    xuat: 'Xuất',
  },
  service: {
    notFound: 'Không tìm thấy phiếu kho',
    saveFailed: 'Lưu phiếu kho thất bại',
  },
} as const;
