import type { LucideIcon } from 'lucide-react';
import {
  BarChart3,
  Boxes,
  BookOpen,
  FlaskConical,
  GitBranch,
  Layers,
  Briefcase,
  Building2,
  CircleDollarSign,
  ClipboardList,
  Factory,
  FileKey,
  FolderTree,
  Home,
  Landmark,
  LayoutDashboard,
  MapPinned,
  Package,
  PieChart,
  Ruler,
  Scale,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  Store,
  Tags,
  Truck,
  Users,
  UsersRound,
  Warehouse,
} from 'lucide-react';

/** Icon theo path — sidebar, Trang chủ, command palette, dashboard card. */
export const NAV_PATH_ICONS: Record<string, LucideIcon> = {
  '/': Home,
  '/thong-tin-ban-quyen': FileKey,
  '/kinh-doanh': Store,
  '/kinh-doanh/don-hang': ShoppingCart,
  '/kinh-doanh/bao-cao-ban-hang': BarChart3,
  '/kinh-doanh/mua-nguyen-lieu': Package,
  '/kinh-doanh/danh-sach-khach-hang': Users,
  '/kinh-doanh/bao-cao-cong-no-khach-hang': Scale,
  '/kinh-doanh/danh-sach-nha-cung-cap': Truck,
  '/kinh-doanh/bao-cao-cong-no-nha-cung-cap': Scale,
  '/san-xuat': Factory,
  '/san-xuat/lenh-san-xuat': ClipboardList,
  '/san-xuat/bao-cao-san-xuat': BarChart3,
  '/san-xuat/phieu-kho': ScrollText,
  '/san-xuat/bao-cao-kho': Warehouse,
  '/san-xuat/danh-muc-hang-hoa': FolderTree,
  '/san-xuat/danh-sach-hang-hoa': Package,
  '/san-xuat/thuoc-tinh-hang-hoa': SlidersHorizontal,
  '/san-xuat/thong-so-do': Ruler,
  '/san-xuat/danh-sach-kho': Boxes,
  '/san-xuat/danh-muc-nguyen-lieu': Layers,
  '/san-xuat/danh-sach-nguyen-lieu': FlaskConical,
  '/san-xuat/bom': GitBranch,
  '/tai-chinh': CircleDollarSign,
  '/he-thong': Settings,
  '/tai-chinh/so-thu-chi': BookOpen,
  '/tai-chinh/tai-khoan': Landmark,
  '/tai-chinh/danh-muc-tai-chinh': Tags,
  '/tai-chinh/tra-cuu-tai-khoan': Search,
  '/tai-chinh/bao-cao-tai-chinh': PieChart,
  '/he-thong/phong-ban': Building2,
  '/he-thong/chuc-vu': Briefcase,
  '/he-thong/nhan-vien': Users,
  '/he-thong/thong-tin-to-chuc': Landmark,
  '/he-thong/chi-nhanh': MapPinned,
  '/he-thong/phan-quyen': Shield,
};

export function navPathIcon(path: string, fallback: LucideIcon = LayoutDashboard): LucideIcon {
  return NAV_PATH_ICONS[path] ?? fallback;
}
