export const productionOrder = {
  title: 'Lệnh sản xuất',
  tabList: 'Danh sách',
  tabLines: 'Chi tiết',
  tabBom: 'BOM',
  noViewPermission: 'Bạn không có quyền xem module Lệnh sản xuất.',
  loading: 'Đang tải lệnh sản xuất...',
  linesLoading: 'Đang tải chi tiết sản phẩm...',
  empty: 'Chưa có lệnh sản xuất',
  linesEmpty: 'Chưa có dòng sản phẩm',
  bomEmpty: 'Chưa có dữ liệu BOM',
  bomEmptyHint: 'BOM của các sản phẩm trong lệnh sản xuất sẽ hiển thị tại đây.',
  bomLoading: 'Đang tải BOM...',
  bomLoadErrorTitle: 'Không tải được BOM',
  bomLoadErrorHint: 'Kiểm tra kết nối Supabase và quyền truy cập.',
  footerBomRecords: 'dòng BOM',
  emptyHint: 'Đơn hàng ở trạng thái «Chuyển sản xuất» hoặc «Hoàn thành» sẽ hiển thị tại đây.',
  linesEmptyHint: 'Các dòng sản phẩm của lệnh sản xuất sẽ hiển thị tại tab này.',
  linesLoadErrorTitle: 'Không tải được chi tiết sản phẩm',
  linesLoadErrorHint: 'Kiểm tra kết nối Supabase và quyền truy cập.',
  footerLineRecords: 'dòng',
  listLoadErrorTitle: 'Không tải được danh sách lệnh sản xuất',
  listLoadErrorHint: 'Kiểm tra kết nối Supabase và quyền truy cập.',
  footerRecords: 'lệnh',
  filter: {
    dateAll: 'Tất cả ngày',
    dateThisMonth: 'Tháng này',
    dateLastMonth: 'Tháng trước',
    dateCustom: 'Tùy chọn',
    orderDate: 'Ngày đặt',
  },
  store: {
    codeCol: 'Mã đơn',
    customerCol: 'Khách hàng',
    orderDateCol: 'Ngày đặt',
    deliveryDateCol: 'Ngày giao',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật',
    branchCol: 'Chi nhánh',
    categoryCol: 'Danh mục SP',
    groupCol: 'Nhóm SP',
    qtyCol: 'Số lượng',
    lineCountCol: 'Số SP',
    bomCountCol: 'Số BOM',
    slReceivedCol: 'SL đã nhập',
    slRemainingCol: 'SL còn lại',
    tienDoCol: 'Tiến độ',
    tienDoTongCol: 'Tiến độ tổng',
    productCol: 'Sản phẩm',
    productQtyCol: 'SL SP',
    materialCol: 'Nguyên liệu',
    bomQtyPerUnitCol: 'SL / SP',
    bomQtyTotalCol: 'SL tổng',
    unitCol: 'Đơn vị',
  },
  progress: {
    chuaSanXuat: 'Chưa sản xuất',
    nhap1Phan: 'Nhập 1 phần',
    hoanThanh: 'Hoàn thành',
  },
  detail: {
    title: 'Chi tiết lệnh sản xuất',
    customerSection: 'Khách hàng',
    orderInfo: 'Thông tin đơn',
    productsSection: 'Sản phẩm',
    linesSection: 'Chi tiết sản phẩm',
    noLines: 'Chưa có dòng sản phẩm',
    orderBomEmpty: 'Chưa có BOM',
    orderBomEmptyHint: 'Sinh BOM từ chi tiết từng sản phẩm hoặc thêm nguyên liệu thủ công.',
    orderBomProductCol: 'Sản phẩm',
    lineDetailTitle: 'Chi tiết dòng sản phẩm',
    systemInfo: 'Thông tin hệ thống',
    viewCustomer: 'Xem khách hàng',
    changeStatus: 'Chuyển trạng thái',
  },
  statusChangeTitle: 'Chuyển trạng thái lệnh sản xuất',
  statusChangeMessage: 'Chọn trạng thái mới cho lệnh',
  validation: {
    invalidStatus: 'Chỉ được chọn trạng thái Chuyển sản xuất hoặc Hoàn thành',
  },
  toast: {
    statusUpdateSuccess: 'Đã cập nhật trạng thái lệnh sản xuất',
  },
  service: {
    notFound: 'Không tìm thấy lệnh sản xuất',
  },
  lineBom: {
    sectionTitle: 'BOM',
    generateFromCategory: 'Sinh BOM từ danh mục',
    addLine: 'Thêm dòng',
    empty: 'Chưa có BOM cho sản phẩm này',
    emptyHint: 'Sinh BOM từ cài đặt danh mục hoặc thêm nguyên liệu thủ công.',
    loading: 'Đang tải BOM...',
    materialCol: 'Nguyên liệu',
    materialCodeCol: 'Mã NL',
    qtyPerUnitCol: 'SL / SP',
    qtyTotalCol: 'SL tổng',
    unitCol: 'Đơn vị',
    noteCol: 'Ghi chú',
    recordCount: 'dòng',
    detailTitle: 'Chi tiết BOM dòng',
    formCreateTitle: 'Thêm nguyên liệu BOM',
    formEditTitle: 'Sửa nguyên liệu BOM',
    formMaterial: 'Nguyên liệu',
    formMaterialPlaceholder: 'Chọn nguyên liệu trong BOM mẫu danh mục',
    formQtyPerUnit: 'Số lượng / SP',
    formUnit: 'Đơn vị',
    formSortOrder: 'Thứ tự',
    formNote: 'Ghi chú',
    materialLocked: 'Nguyên liệu không thể đổi khi sửa.',
    replaceTitle: 'Ghi đè BOM hiện tại?',
    replaceMessage: 'BOM cũ sẽ bị xóa và sinh lại từ mẫu danh mục.',
    deleteTitle: 'Xóa dòng BOM?',
    deleteMessage: 'Dòng BOM này sẽ bị xóa khỏi lệnh sản xuất.',
    validation: {
      materialRequired: 'Chọn nguyên liệu',
      quantityRequired: 'Nhập số lượng / SP lớn hơn 0',
    },
    toast: {
      generateSuccess: 'Đã sinh BOM từ danh mục',
      createSuccess: 'Đã thêm dòng BOM',
      updateSuccess: 'Đã cập nhật dòng BOM',
      deleteSuccess: 'Đã xóa dòng BOM',
    },
    service: {
      notFound: 'Không tìm thấy dòng BOM',
      saveFailed: 'Lưu BOM thất bại',
    },
  },
} as const;
