/** Tài khoản / quỹ thu chi */
export const financeAccount = {
  noViewPermission: 'Bạn không có quyền xem module Tài khoản.',
  title: 'Tài khoản',
  deleteTitle: 'Xóa tài khoản',
  deleteMessage: 'Bạn có chắc chắn muốn xóa tài khoản / quỹ này không?',
  bulkDeleteTitle: 'Xóa nhiều tài khoản',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} tài khoản đã chọn?',
  statusChangeTitle: 'Chuyển trạng thái tài khoản',
  statusChangeMessage: 'Bạn có muốn chuyển trạng thái {{count}} tài khoản sang',
  noExportData: 'Không có dữ liệu để xuất',
  exportName: 'Tên quỹ',
  exportFundType: 'Loại quỹ',
  exportBranch: 'Chi nhánh',
  exportBank: 'Ngân hàng',
  exportBin: 'Mã BIN',
  exportAccountNo: 'Số tài khoản',
  exportHolder: 'Chủ tài khoản',
  exportOpeningBalance: 'Số dư khởi đầu',
  exportStatus: 'Trạng thái',
  importTemplateName: 'Mau_Import_Tai_Khoan',
  active: 'Hoạt động',
  inactive: 'Ngừng',
  loading: 'Đang tải danh sách tài khoản...',
  empty: 'Chưa có tài khoản / quỹ nào',
  emptyHint: 'Hãy tạo quỹ tiền mặt hoặc tài khoản ngân hàng đầu tiên.',
  listLoadErrorTitle: 'Không tải được danh sách tài khoản',
  listLoadErrorHint:
    'Kiểm tra kết nối Supabase, đăng nhập (RLS) và migration tc_tai_khoan. Thử tải lại.',
  footerRecords: 'tài khoản',
  fundTypeCash: 'Tiền mặt',
  fundTypeBank: 'Ngân hàng',
  form: {
    editTitle: 'Chỉnh sửa Tài khoản',
    createTitle: 'Thêm Tài khoản mới',
    editSubtitle: 'Cập nhật quỹ / tài khoản hiện có',
    createSubtitle: 'Khai báo quỹ tiền mặt hoặc tài khoản ngân hàng',
    generalInfo: 'Thông tin chung',
    bankInfo: 'Thông tin ngân hàng',
    name: 'Tên quỹ',
    namePlaceholder: 'VD: Quỹ tiền mặt HCM',
    fundType: 'Loại quỹ',
    branch: 'Chi nhánh',
    branchPlaceholder: 'Chọn chi nhánh',
    bank: 'Ngân hàng',
    bankPlaceholder: 'Chọn ngân hàng',
    accountNumber: 'Số tài khoản',
    accountNumberPlaceholder: 'Chỉ nhập số, không dấu cách',
    accountHolder: 'Chủ tài khoản',
    accountHolderPlaceholder: 'Tên in trên tài khoản (không dấu hoặc có dấu)',
    openingBalance: 'Số dư khởi đầu',
    status: 'Trạng thái',
    validationError: 'Vui lòng kiểm tra các trường bắt buộc và thử lại.',
    qrSection: 'Mã QR thanh toán (VietQR)',
    qrHint: 'Nhập đủ ngân hàng, số tài khoản và chủ tài khoản để xem mã QR.',
  },
  detail: {
    title: 'Chi tiết Tài khoản',
    subtitle: 'Thông tin quỹ / tài khoản',
    basicInfo: 'Thông tin cơ bản',
    bankInfo: 'Ngân hàng',
    qrSection: 'Mã QR thanh toán',
    systemInfo: 'Hệ thống',
    createdAt: 'Ngày tạo',
    updated: 'Cập nhật',
    activate: 'Kích hoạt',
    deactivate: 'Ngừng hoạt động',
  },
  store: {
    nameCol: 'Tên quỹ',
    fundTypeCol: 'Loại quỹ',
    branchCol: 'Chi nhánh',
    bankCol: 'Ngân hàng',
    accountNoCol: 'Số TK',
    openingBalanceCol: 'Số dư KĐ',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật cuối',
  },
  validation: {
    nameMin: 'Tên quỹ phải có ít nhất 2 ký tự',
    nameMax: 'Tên quỹ quá dài',
    fundTypeInvalid: 'Loại quỹ không hợp lệ',
    branchRequired: 'Vui lòng chọn chi nhánh',
    bankRequired: 'Vui lòng chọn ngân hàng',
    accountNumberRequired: 'Vui lòng nhập số tài khoản',
    accountNumberFormat: 'Số tài khoản chỉ gồm chữ số',
    accountHolderRequired: 'Vui lòng nhập chủ tài khoản',
    balanceMin: 'Số dư khởi đầu không được âm',
    statusInvalid: 'Trạng thái không hợp lệ',
  },
  toast: {
    createSuccess: 'Tạo tài khoản thành công',
    updateSuccess: 'Cập nhật thành công',
    statusUpdate: 'Đã cập nhật trạng thái {{count}} bản ghi',
    deleteSuccess: 'Đã xóa thành công {{count}} tài khoản',
    importSuccess: 'Đã nhập {{count}} tài khoản',
  },
  service: {
    duplicateName: 'Tên quỹ đã tồn tại',
    notFound: 'Không tìm thấy tài khoản',
    createFetchFailed: 'Tạo thành công nhưng không tải lại được bản ghi',
  },
  qr: {
    placeholder: 'Nhập đủ thông tin ngân hàng để hiển thị mã QR',
    download: 'Tải ảnh QR',
    copyLink: 'Sao chép link ảnh',
    copied: 'Đã sao chép link ảnh QR',
  },
};
