/** Danh sách hàng hóa */
export const productCatalog = {
  noViewPermission: 'Bạn không có quyền xem module Danh sách hàng hóa.',
  title: 'Danh sách hàng hóa',
  deleteTitle: 'Xóa sản phẩm',
  deleteMessage: 'Bạn có chắc chắn muốn xóa sản phẩm này không?',
  bulkDeleteTitle: 'Xóa nhiều sản phẩm',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} sản phẩm đã chọn?',
  statusChangeTitle: 'Chuyển trạng thái sản phẩm',
  statusChangeMessage: 'Bạn có muốn chuyển trạng thái {{count}} sản phẩm sang',
  loading: 'Đang tải danh sách hàng hóa...',
  empty: 'Chưa có sản phẩm nào',
  emptyHint: 'Hãy tạo sản phẩm đầu tiên và chọn danh mục cấp 2.',
  listLoadErrorTitle: 'Không tải được danh sách hàng hóa',
  listLoadErrorHint:
    'Kiểm tra kết nối Supabase, đăng nhập và migration sx_danh_sach_san_pham. Thử tải lại.',
  form: {
    editTitle: 'Chỉnh sửa sản phẩm',
    createTitle: 'Thêm sản phẩm mới',
    editSubtitle: 'Cập nhật thông tin sản phẩm',
    createSubtitle: 'Khai báo hàng hóa thuộc danh mục cấp 2',
    generalInfo: 'Thông tin sản phẩm',
    code: 'Mã sản phẩm',
    codePlaceholder: 'VD: AO-001',
    name: 'Tên sản phẩm',
    namePlaceholder: 'VD: Áo sơ mi trắng',
    category: 'Danh mục',
    categoryPlaceholder: 'Chọn danh mục cấp 2…',
    description: 'Mô tả',
    descriptionPlaceholder: 'Mô tả ngắn…',
    status: 'Trạng thái',
    attributesSection: 'Thuộc tính',
    attributesEmpty: 'Danh mục chưa gán thuộc tính — chọn danh mục khác hoặc cấu hình tại Danh mục hàng hóa.',
    selectCategoryFirst: 'Chọn danh mục để nhập thuộc tính.',
    categoryChanged: 'Đã đổi danh mục — danh sách thuộc tính được cập nhật theo danh mục mới.',
    validationError: 'Vui lòng kiểm tra các trường bắt buộc và thử lại.',
  },
  detail: {
    title: 'Chi tiết sản phẩm',
    subtitle: 'Thông tin hàng hóa',
    basicInfo: 'Thông tin cơ bản',
    systemInfo: 'Hệ thống',
    categoryGroup: 'Nhóm danh mục',
    category: 'Danh mục',
    attributesSection: 'Thuộc tính',
    noAttributes: 'Chưa có giá trị thuộc tính',
    createdAt: 'Ngày tạo',
    updated: 'Cập nhật',
    activate: 'Kích hoạt',
    deactivate: 'Ngừng hoạt động',
  },
  store: {
    codeCol: 'Mã SP',
    nameCol: 'Tên sản phẩm',
    categoryCol: 'Danh mục',
    groupCol: 'Nhóm',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật',
  },
  validation: {
    codeRequired: 'Vui lòng nhập mã sản phẩm',
    codeMax: 'Mã sản phẩm quá dài',
    nameRequired: 'Vui lòng nhập tên sản phẩm',
    nameMax: 'Tên sản phẩm quá dài',
    categoryRequired: 'Vui lòng chọn danh mục cấp 2',
    statusInvalid: 'Trạng thái không hợp lệ',
    attributeRequired: '{{name}} là bắt buộc',
  },
  toast: {
    createSuccess: 'Tạo sản phẩm thành công',
    updateSuccess: 'Cập nhật thành công',
    statusUpdate: 'Đã cập nhật trạng thái {{count}} sản phẩm',
    deleteSuccess: 'Đã xóa thành công {{count}} sản phẩm',
  },
  service: {
    duplicateCode: 'Mã sản phẩm đã tồn tại',
    notFound: 'Không tìm thấy sản phẩm',
    createFetchFailed: 'Tạo thành công nhưng không tải lại được bản ghi',
    invalidAttribute: 'Thuộc tính không hợp lệ với danh mục đã chọn',
  },
};
