export const salesOrder = {
  title: 'Đơn hàng',
  noViewPermission: 'Bạn không có quyền xem module Đơn hàng.',
  addButton: 'Thêm đơn hàng',
  deleteTitle: 'Xóa đơn hàng',
  deleteMessage: 'Bạn có chắc chắn muốn xóa đơn hàng này?',
  deleteBlockedStatus: 'Chỉ xóa được đơn ở trạng thái Nháp hoặc Mới.',
  bulkDeleteTitle: 'Xóa nhiều đơn hàng',
  bulkDeleteMessage: 'Xóa {{count}} đơn hàng đã chọn?',
  loading: 'Đang tải đơn hàng...',
  empty: 'Chưa có đơn hàng',
  emptyHint: 'Tạo đơn bán hàng mới cho khách hàng.',
  listLoadErrorTitle: 'Không tải được danh sách đơn hàng',
  listLoadErrorHint: 'Kiểm tra kết nối Supabase và migration kd_don_hang.',
  footerRecords: 'đơn hàng',
  filter: {
    dateAll: 'Tất cả ngày',
    dateThisMonth: 'Tháng này',
    dateLastMonth: 'Tháng trước',
    dateCustom: 'Tùy chọn',
    orderDate: 'Ngày đặt',
  },
  store: {
    codeCol: 'Mã đơn',
    customerCol: 'Khách hàng',
    orderDateCol: 'Ngày đặt',
    deliveryDateCol: 'Ngày giao',
    totalCol: 'Tổng tiền',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật',
    branchCol: 'Chi nhánh',
  },
  form: {
    createTitle: 'Thêm đơn hàng',
    createSubtitle: 'Nhập thông tin đơn và ít nhất một dòng sản phẩm.',
    editTitle: 'Sửa đơn hàng',
    editSubtitle: 'Đơn {{code}}',
    addLineHint: 'Thêm ít nhất một sản phẩm vào đơn.',
    codePlaceholder: 'Để trống để tự sinh mã',
    customer: 'Khách hàng',
    customerPlaceholder: 'Chọn khách hàng',
    orderDate: 'Ngày đặt',
    deliveryDate: 'Ngày giao dự kiến',
    branch: 'Chi nhánh',
    branchNone: '— Không chọn —',
    deliveryAddress: 'Địa chỉ giao',
    note: 'Ghi chú',
    linesSection: 'Chi tiết sản phẩm',
    addLine: 'Thêm dòng',
    product: 'Sản phẩm',
    qty: 'Số lượng',
    unit: 'ĐVT',
    unitPrice: 'Đơn giá',
    lineTotal: 'Thành tiền',
    lineNote: 'Ghi chú dòng',
    orderTotal: 'Tổng đơn',
    validationError: 'Vui lòng kiểm tra lại thông tin form.',
  },
  detail: {
    title: 'Chi tiết đơn hàng',
    customerSection: 'Khách hàng',
    orderInfo: 'Thông tin đơn',
    linesSection: 'Chi tiết sản phẩm',
    noLines: 'Chưa có dòng sản phẩm',
    systemInfo: 'Thông tin hệ thống',
    viewCustomer: 'Xem khách hàng',
    addOrEditLines: 'Sửa dòng SP',
    deleteLineTitle: 'Xóa dòng sản phẩm',
    deleteLineMessage: 'Xóa dòng «{{product}}» khỏi đơn {{code}}?',
    createOrderForCustomer: 'Tạo đơn hàng',
    recentOrders: 'Đơn hàng gần đây',
    noRecentOrders: 'Chưa có đơn hàng',
  },
  validation: {
    customerRequired: 'Vui lòng chọn khách hàng',
    orderDateRequired: 'Vui lòng chọn ngày đặt',
    productRequired: 'Vui lòng chọn sản phẩm',
    qtyPositive: 'Số lượng phải lớn hơn 0',
    priceMin: 'Đơn giá không được âm',
    linesMin: 'Cần ít nhất một dòng sản phẩm',
  },
  toast: {
    createSuccess: 'Tạo đơn hàng thành công',
    updateSuccess: 'Cập nhật đơn hàng thành công',
    deleteSuccess: 'Đã xóa đơn hàng',
  },
  service: {
    notFound: 'Không tìm thấy đơn hàng',
    saveFailed: 'Lưu đơn hàng thất bại',
  },
  status: {
    nhap: 'Nháp',
    moi: 'Mới',
    hoanThanh: 'Hoàn thành',
    huy: 'Hủy',
  },
} as const;
