export const salesOrder = {
  title: 'Đơn hàng',
  noViewPermission: 'Bạn không có quyền xem module Đơn hàng.',
  addButton: 'Thêm đơn hàng',
  deleteTitle: 'Xóa đơn hàng',
  deleteMessage: 'Bạn có chắc chắn muốn xóa đơn hàng này?',
  deleteBlockedStatus: 'Chỉ xóa được đơn ở trạng thái Nháp hoặc Mới.',
  statusChangeTitle: 'Chuyển trạng thái đơn hàng',
  statusChangeMessage: 'Chọn trạng thái mới cho đơn',
  bulkDeleteTitle: 'Xóa nhiều đơn hàng',
  bulkDeleteMessage: 'Xóa {{count}} đơn hàng đã chọn?',
  loading: 'Đang tải đơn hàng...',
  empty: 'Chưa có đơn hàng',
  emptyHint: 'Tạo đơn bán hàng mới cho khách hàng.',
  listLoadErrorTitle: 'Không tải được danh sách đơn hàng',
  listLoadErrorHint: 'Kiểm tra kết nối Supabase và migration kd_don_hang.',
  footerRecords: 'đơn hàng',
  filter: {
    dateAll: 'Tất cả ngày',
    dateThisMonth: 'Tháng này',
    dateLastMonth: 'Tháng trước',
    dateCustom: 'Tùy chọn',
    orderDate: 'Ngày đặt',
  },
  store: {
    codeCol: 'Mã đơn',
    customerCol: 'Khách hàng',
    orderDateCol: 'Ngày đặt',
    deliveryDateCol: 'Ngày giao',
    totalCol: 'Tổng tiền',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật',
    branchCol: 'Chi nhánh',
    slDonDatCol: 'SL đơn đặt',
    slDaSxCol: 'SL đã SX',
    slConLaiCol: 'SL còn lại',
    tienDoCol: 'Tiến độ',
  },
  form: {
    createTitle: 'Thêm đơn hàng',
    createSubtitle: 'Nhập thông tin đơn và thêm sản phẩm vào bảng bên dưới.',
    editTitle: 'Sửa đơn hàng',
    editSubtitle: 'Đơn {{code}}',
    addLineHint: 'Bấm Thêm dòng để chọn loại hàng, thuộc tính và thông số đo.',
    codePlaceholder: 'Để trống để tự sinh mã',
    customer: 'Khách hàng',
    customerPlaceholder: 'Chọn khách hàng',
    orderDate: 'Ngày đặt',
    deliveryDate: 'Ngày giao dự kiến',
    branch: 'Chi nhánh',
    branchNone: '— Không chọn —',
    deliveryAddress: 'Địa chỉ giao',
    note: 'Ghi chú',
    linesSection: 'Chi tiết sản phẩm',
    addLine: 'Thêm dòng',
    category: 'Loại hàng',
    categoryPlaceholder: 'Chọn loại hàng',
    qty: 'Số lượng',
    unit: 'ĐVT',
    unitPrice: 'Đơn giá',
    lineTotal: 'Thành tiền',
    lineNote: 'Ghi chú dòng',
    orderTotal: 'Tổng đơn',
    attributesSection: 'Thuộc tính',
    attributesEmpty: 'Danh mục sản phẩm chưa cấu hình thuộc tính.',
    measurementsSection: 'Thông số đo',
    measurementsEmpty: 'Danh mục sản phẩm chưa cấu hình thông số đo.',
    categoryChangedResetSpecs: 'Đã đổi loại hàng — thuộc tính và thông số đo được làm mới theo danh mục.',
    validationError: 'Vui lòng kiểm tra lại thông tin form.',
    addLineTitle: 'Thêm sản phẩm',
    editLineTitle: 'Sửa dòng sản phẩm',
    addLineSubtitle: 'Đơn {{code}}',
    editLineSubtitle: '{{category}} · Đơn {{code}}',
  },
  detail: {
    title: 'Chi tiết đơn hàng',
    customerSection: 'Khách hàng',
    orderInfo: 'Thông tin đơn',
    linesSection: 'Chi tiết sản phẩm',
    noLines: 'Chưa có dòng sản phẩm',
    lineDetailTitle: 'Chi tiết dòng sản phẩm',
    systemInfo: 'Thông tin hệ thống',
    viewCustomer: 'Xem khách hàng',
    deleteLineTitle: 'Xóa dòng sản phẩm',
    deleteLineMessage: 'Xóa dòng «{{category}}» khỏi đơn {{code}}?',
    createOrderForCustomer: 'Tạo đơn hàng',
    recentOrders: 'Đơn hàng gần đây',
    noRecentOrders: 'Chưa có đơn hàng',
    changeStatus: 'Chuyển trạng thái',
  },
  validation: {
    customerRequired: 'Vui lòng chọn khách hàng',
    orderDateRequired: 'Vui lòng chọn ngày đặt',
    categoryRequired: 'Vui lòng chọn loại hàng',
    qtyPositive: 'Số lượng phải lớn hơn 0',
    priceMin: 'Đơn giá không được âm',
    linesMin: 'Cần ít nhất một dòng sản phẩm',
    attributeRequired: 'Vui lòng nhập thuộc tính «{{name}}»',
    measurementRequired: 'Vui lòng nhập thông số đo «{{name}}»',
    specsIncomplete: 'Vui lòng điền đủ thuộc tính và thông số đo của loại hàng.',
    specsLoading: 'Đang tải thuộc tính và thông số đo — vui lòng thử lại.',
  },
  toast: {
    createSuccess: 'Tạo đơn hàng thành công',
    updateSuccess: 'Cập nhật đơn hàng thành công',
    deleteSuccess: 'Đã xóa đơn hàng',
    statusUpdateSuccess: 'Đã cập nhật trạng thái đơn hàng',
  },
  service: {
    notFound: 'Không tìm thấy đơn hàng',
    saveFailed: 'Lưu đơn hàng thất bại',
  },
  status: {
    nhap: 'Nháp',
    moi: 'Mới',
    chuyenSanXuat: 'Chuyển sản xuất',
    hoanThanh: 'Hoàn thành',
    huy: 'Hủy',
  },
} as const;
