export const purchaseOrder = {
  title: 'Mua nguyên liệu',
  noViewPermission: 'Bạn không có quyền xem module Mua nguyên liệu.',
  addButton: 'Thêm đơn mua',
  deleteTitle: 'Xóa đơn mua',
  deleteMessage: 'Bạn có chắc chắn muốn xóa đơn mua này?',
  deleteBlockedStatus: 'Chỉ xóa được đơn ở trạng thái Nháp hoặc Đã đặt.',
  editBlockedStatus: 'Chỉ sửa được đơn ở trạng thái Nháp.',
  statusChangeTitle: 'Chuyển trạng thái đơn mua',
  statusChangeMessage: 'Chọn trạng thái mới cho đơn',
  bulkDeleteTitle: 'Xóa nhiều đơn mua',
  bulkDeleteMessage: 'Xóa {{count}} đơn mua đã chọn?',
  loading: 'Đang tải đơn mua...',
  empty: 'Chưa có đơn mua',
  emptyHint: 'Tạo đơn mua nguyên liệu mới từ nhà cung cấp.',
  listLoadErrorTitle: 'Không tải được danh sách đơn mua',
  listLoadErrorHint: 'Kiểm tra kết nối Supabase và migration kd_don_mua.',
  footerRecords: 'đơn mua',
  filter: {
    dateAll: 'Tất cả ngày',
    dateThisMonth: 'Tháng này',
    dateLastMonth: 'Tháng trước',
    dateCustom: 'Tùy chọn',
    orderDate: 'Ngày đặt',
  },
  store: {
    codeCol: 'Mã đơn',
    supplierCol: 'Nhà cung cấp',
    orderDateCol: 'Ngày đặt',
    deliveryDateCol: 'Ngày giao',
    totalCol: 'Tổng tiền',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật',
    branchCol: 'Chi nhánh',
  },
  form: {
    createTitle: 'Thêm đơn mua',
    createSubtitle: 'Nhập thông tin đơn, thêm dòng nguyên liệu từ bảng chi tiết.',
    editTitle: 'Sửa đơn mua',
    editSubtitle: 'Đơn {{code}}',
    addLineHint: 'Thêm ít nhất một nguyên liệu vào đơn.',
    codePlaceholder: 'Để trống để tự sinh mã',
    supplier: 'Nhà cung cấp',
    supplierPlaceholder: 'Chọn nhà cung cấp',
    orderDate: 'Ngày đặt',
    deliveryDate: 'Ngày giao dự kiến',
    branch: 'Chi nhánh',
    branchNone: '— Không chọn —',
    receiveAddress: 'Địa chỉ nhận',
    note: 'Ghi chú',
    linesSection: 'Chi tiết nguyên liệu',
    addLine: 'Thêm dòng',
    material: 'Nguyên liệu',
    qty: 'Số lượng',
    unit: 'ĐVT',
    unitPrice: 'Đơn giá',
    lineTotal: 'Thành tiền',
    lineNote: 'Ghi chú dòng',
    orderTotal: 'Tổng đơn',
    validationError: 'Vui lòng kiểm tra lại thông tin form.',
    addLineTitle: 'Thêm nguyên liệu',
    editLineTitle: 'Sửa dòng nguyên liệu',
    addLineSubtitle: 'Đơn {{code}}',
    editLineSubtitle: '{{material}} · Đơn {{code}}',
  },
  detail: {
    title: 'Chi tiết đơn mua',
    supplierSection: 'Nhà cung cấp',
    orderInfo: 'Thông tin đơn',
    linesSection: 'Chi tiết nguyên liệu',
    noLines: 'Chưa có dòng nguyên liệu',
    systemInfo: 'Thông tin hệ thống',
    viewSupplier: 'Xem nhà cung cấp',
    deleteLineTitle: 'Xóa dòng nguyên liệu',
    deleteLineMessage: 'Xóa dòng «{{material}}» khỏi đơn {{code}}?',
    changeStatus: 'Chuyển trạng thái',
  },
  validation: {
    supplierRequired: 'Vui lòng chọn nhà cung cấp',
    orderDateRequired: 'Vui lòng chọn ngày đặt',
    materialRequired: 'Vui lòng chọn nguyên liệu',
    qtyPositive: 'Số lượng phải lớn hơn 0',
    priceMin: 'Đơn giá không được âm',
    linesMin: 'Cần ít nhất một dòng nguyên liệu',
  },
  toast: {
    createSuccess: 'Tạo đơn mua thành công',
    updateSuccess: 'Cập nhật đơn mua thành công',
    deleteSuccess: 'Đã xóa đơn mua',
    statusUpdateSuccess: 'Đã cập nhật trạng thái đơn mua',
  },
  service: {
    notFound: 'Không tìm thấy đơn mua',
    saveFailed: 'Lưu đơn mua thất bại',
  },
  status: {
    nhap: 'Nháp',
    daDat: 'Đã đặt',
    dangGiao: 'Đang giao',
    daNhan: 'Đã nhận',
    huy: 'Hủy',
  },
} as const;
