/** BOM — định mức nguyên vật liệu */
export const bom = {
  noViewPermission: 'Bạn không có quyền xem module BOM.',
  title: 'BOM',
  deleteTitle: 'Xóa định mức',
  deleteMessage: 'Bạn có chắc chắn muốn xóa dòng định mức này không?',
  bulkDeleteTitle: 'Xóa nhiều định mức',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} dòng định mức đã chọn?',
  statusChangeTitle: 'Chuyển trạng thái định mức',
  statusChangeMessage: 'Bạn có muốn chuyển trạng thái {{count}} dòng sang',
  loading: 'Đang tải danh sách định mức...',
  empty: 'Chưa có định mức nào',
  emptyHint: 'Thêm dòng định mức nguyên liệu cho sản phẩm.',
  listLoadErrorTitle: 'Không tải được danh sách định mức',
  listLoadErrorHint:
    'Kiểm tra kết nối Supabase, đăng nhập và migration sx_bom. Thử tải lại.',
  form: {
    editTitle: 'Chỉnh sửa định mức',
    createTitle: 'Thêm định mức',
    editSubtitle: 'Cập nhật số lượng nguyên liệu cho sản phẩm',
    createSubtitle: 'Khai báo một dòng định mức SP + nguyên liệu',
    generalInfo: 'Thông tin định mức',
    product: 'Sản phẩm',
    productPlaceholder: 'Chọn sản phẩm…',
    productLocked: 'Sản phẩm và nguyên liệu không đổi sau khi tạo (xóa và tạo lại nếu cần đổi cặp).',
    material: 'Nguyên liệu',
    materialPlaceholder: 'Chọn nguyên liệu…',
    quantity: 'Số lượng',
    unit: 'ĐVT',
    lineNote: 'Ghi chú',
    sortOrder: 'Thứ tự',
    status: 'Trạng thái',
    validationError: 'Vui lòng kiểm tra các trường bắt buộc và thử lại.',
  },
  detail: {
    title: 'Chi tiết định mức',
    subtitle: 'Định mức nguyên vật liệu',
    basicInfo: 'Thông tin định mức',
    productSection: 'Sản phẩm',
    materialSection: 'Nguyên liệu',
    systemInfo: 'Hệ thống',
    categoryGroup: 'Nhóm danh mục SP',
    category: 'Danh mục SP',
    createdAt: 'Ngày tạo',
    updated: 'Cập nhật',
    activate: 'Kích hoạt',
    deactivate: 'Ngừng hoạt động',
  },
  store: {
    productCodeCol: 'Mã SP',
    productNameCol: 'Tên sản phẩm',
    materialCodeCol: 'Mã NL',
    materialNameCol: 'Tên nguyên liệu',
    quantityCol: 'Số lượng',
    unitCol: 'ĐVT',
    groupCol: 'Nhóm DM',
    categoryCol: 'Danh mục SP',
    sortCol: 'Thứ tự',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật',
  },
  validation: {
    productRequired: 'Vui lòng chọn sản phẩm',
    materialRequired: 'Vui lòng chọn nguyên liệu',
    statusInvalid: 'Trạng thái không hợp lệ',
    quantityRequired: 'Số lượng phải lớn hơn 0',
  },
  toast: {
    createSuccess: 'Thêm định mức thành công',
    updateSuccess: 'Cập nhật thành công',
    statusUpdate: 'Đã cập nhật trạng thái {{count}} dòng',
    deleteSuccess: 'Đã xóa thành công {{count}} dòng',
  },
  service: {
    duplicatePair: 'Sản phẩm đã có định mức cho nguyên liệu này',
    notFound: 'Không tìm thấy định mức',
    createFetchFailed: 'Tạo thành công nhưng không tải lại được bản ghi',
  },
  embedded: {
    sectionTitle: 'BOM — Định mức',
    addLine: 'Thêm định mức',
    recordCount: 'dòng',
    noPermission: 'Bạn không có quyền xem BOM.',
    empty: 'Chưa có định mức',
    emptyProductHint: 'Thêm nguyên liệu vào định mức cho sản phẩm này.',
    emptyMaterialHint: 'Thêm sản phẩm dùng nguyên liệu này vào định mức.',
  },
};
