/** Nhóm đối tác kinh doanh */
export const partnerCategory = {
  kindCustomer: 'Khách hàng',
  kindSupplier: 'Nhà cung cấp',
  exportName: 'Tên nhóm',
  exportCode: 'Mã nhóm',
  exportLevel: 'Cấp độ',
  exportOrder: 'Thứ tự',
  exportStatus: 'Trạng thái',
  exportParent: 'Nhóm cha',
  noExportData: 'Không có dữ liệu để xuất',
  toolbar: {
    rootCategory: 'Nhóm gốc',
  },
  footerRecords: 'bản ghi',
  title: 'Nhóm đối tác',
  noViewPermission: 'Bạn không có quyền xem module nhóm đối tác.',
  addButton: 'Thêm nhóm',
  deleteTitle: 'Xóa nhóm',
  deleteMessage:
    'Bạn có chắc chắn muốn xóa nhóm này? Không thể xóa nếu đang có nhóm con.',
  loading: 'Đang tải nhóm đối tác...',
  empty: 'Chưa có nhóm nào',
  emptyHint: 'Hãy tạo nhóm gốc để bắt đầu phân loại đối tác.',
  listLoadErrorTitle: 'Không tải được danh sách nhóm',
  listLoadErrorHint:
    'Kiểm tra kết nối Supabase, đăng nhập và migration kd_danh_muc_doi_tac. Thử tải lại.',
  name: 'Tên nhóm',
  code: 'Mã nhóm',
  levelBadge: 'Cấp {{level}}',
  active: 'Hoạt động',
  inactive: 'Ngừng',
  form: {
    editTitle: 'Chỉnh sửa nhóm',
    createTitle: 'Thêm nhóm mới',
    namePlaceholder: 'VD: Khách hàng doanh nghiệp',
    codePlaceholder: 'VD: KHDN (tùy chọn)',
    parentNone: '-- Không (Nhóm gốc) --',
    parentHint: 'Chỉ chọn nhóm cấp 1 làm cha.',
    descriptionPlaceholder: 'Mô tả ngắn về nhóm...',
  },
  validation: {
    nameMin: 'Tên nhóm phải có ít nhất 2 ký tự',
    nameMax: 'Tên nhóm quá dài',
    codeMax: 'Mã nhóm tối đa 50 ký tự',
    statusInvalid: 'Trạng thái không hợp lệ',
    sortOrderMin: 'Thứ tự phải lớn hơn hoặc bằng 0',
  },
  toast: {
    createSuccess: 'Tạo nhóm thành công',
    updateSuccess: 'Cập nhật thành công',
    deleteSuccess: 'Xóa nhóm thành công',
    importSuccess: 'Đã import {{count}} nhóm',
  },
  importTemplateName: 'Mau_Import_Nhom_Doi_Tac',
  import: {
    parentMissing: 'Dòng {{row}}: Nhóm cha không tồn tại',
    parentNotRoot: 'Dòng {{row}}: Cha phải là nhóm cấp 1',
  },
  service: {
    notFound: 'Nhóm không tồn tại',
    hasChildren: 'Không thể xóa nhóm đang có nhóm con.',
    parentNotFound: 'Nhóm cha không tồn tại',
    parentNotRoot: 'Chỉ được chọn nhóm cấp 1 làm cha.',
    level2ParentLocked: 'Nhóm cấp 2 không thể đổi nhóm cha.',
  },
  detail: {
    title: 'Chi tiết nhóm',
    activate: 'Kích hoạt',
    deactivate: 'Ngưng',
    level: 'Cấp độ',
    order: 'Thứ tự',
    parent: 'Nhóm cha',
    noParent: '— Nhóm gốc —',
    updated: 'Cập nhật',
    createdAt: 'Được tạo lúc',
    basicInfo: 'Thông tin cơ bản',
    systemInfo: 'Thông tin hệ thống',
    description: 'Mô tả',
    childrenSection: 'Nhóm con',
    addChild: 'Thêm con',
    noChildren: 'Chưa có nhóm con',
    noChildrenHint: 'Bấm Thêm để tạo nhóm cấp 2 trực tiếp.',
    partnersSection: 'Danh sách đối tác',
    noPartners: 'Chưa có đối tác trong nhóm này',
    noPartnersHint: 'Thêm đối tác thuộc nhóm cấp 2 tại tab Danh sách.',
    addPartner: 'Thêm đối tác',
    noListPermission: 'Bạn không có quyền xem danh sách đối tác.',
    openPartnerList: 'Mở danh sách đối tác',
  },
  store: {
    orderCol: 'Thứ tự',
    nameCol: 'Tên nhóm',
    codeCol: 'Mã',
    descCol: 'Mô tả',
    levelCol: 'Cấp',
    statusCol: 'Trạng thái',
    parentCol: 'Nhóm cha',
    updatedCol: 'Cập nhật',
  },
  statusChangeTitle: 'Chuyển trạng thái nhóm',
  statusChangeMessage: 'Chuyển "{{name}}" sang trạng thái {{status}}?',
  tabLabel: 'Nhóm',
} as const;

/** Danh sách đối tác kinh doanh */
export const partnerList = {
  noViewPermission: 'Bạn không có quyền xem module danh sách đối tác.',
  title: 'Danh sách đối tác',
  deleteTitle: 'Xóa đối tác',
  deleteMessage: 'Bạn có chắc chắn muốn xóa đối tác này không?',
  bulkDeleteTitle: 'Xóa nhiều đối tác',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} đối tác đã chọn?',
  statusChangeTitle: 'Chuyển trạng thái đối tác',
  statusChangeMessage: 'Bạn có muốn chuyển trạng thái {{count}} đối tác sang',
  loading: 'Đang tải danh sách đối tác...',
  empty: 'Chưa có đối tác nào',
  emptyHint: 'Hãy tạo đối tác đầu tiên và chọn nhóm cấp 2.',
  listLoadErrorTitle: 'Không tải được danh sách đối tác',
  listLoadErrorHint:
    'Kiểm tra kết nối Supabase, đăng nhập và migration kd_danh_sach_doi_tac. Thử tải lại.',
  active: 'Hoạt động',
  inactive: 'Ngừng',
  form: {
    editTitle: 'Chỉnh sửa đối tác',
    createTitle: 'Thêm đối tác mới',
    editSubtitle: 'Cập nhật thông tin đối tác',
    createSubtitle: 'Khai báo đối tác thuộc nhóm cấp 2',
    generalInfo: 'Thông tin đối tác',
    contactInfo: 'Liên hệ',
    code: 'Mã đối tác',
    codePlaceholder: 'VD: KH-001',
    name: 'Tên đối tác',
    namePlaceholder: 'VD: Công ty ABC',
    category: 'Nhóm',
    categoryPlaceholder: 'Chọn nhóm cấp 2…',
    phone: 'Điện thoại',
    phonePlaceholder: 'VD: 0901234567',
    email: 'Email',
    emailPlaceholder: 'VD: contact@example.com',
    address: 'Địa chỉ',
    addressPlaceholder: 'Địa chỉ liên hệ…',
    taxCode: 'Mã số thuế',
    taxCodePlaceholder: 'MST…',
    contactPerson: 'Người liên hệ',
    contactPersonPlaceholder: 'Họ tên người liên hệ…',
    description: 'Mô tả',
    descriptionPlaceholder: 'Mô tả ngắn…',
    status: 'Trạng thái',
    validationError: 'Vui lòng kiểm tra các trường bắt buộc và thử lại.',
  },
  detail: {
    title: 'Chi tiết đối tác',
    basicInfo: 'Thông tin cơ bản',
    contactInfo: 'Liên hệ',
    systemInfo: 'Hệ thống',
    categoryGroup: 'Nhóm',
    category: 'Nhóm cấp 2',
    createdAt: 'Ngày tạo',
    updated: 'Cập nhật',
    activate: 'Kích hoạt',
    deactivate: 'Ngừng hoạt động',
  },
  store: {
    codeCol: 'Mã',
    nameCol: 'Tên đối tác',
    categoryCol: 'Nhóm cấp 2',
    groupCol: 'Nhóm',
    phoneCol: 'Điện thoại',
    emailCol: 'Email',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật',
  },
  validation: {
    codeRequired: 'Vui lòng nhập mã đối tác',
    codeMax: 'Mã đối tác quá dài',
    nameRequired: 'Vui lòng nhập tên đối tác',
    nameMax: 'Tên đối tác quá dài',
    categoryRequired: 'Vui lòng chọn nhóm cấp 2',
    statusInvalid: 'Trạng thái không hợp lệ',
    emailInvalid: 'Email không hợp lệ',
  },
  toast: {
    createSuccess: 'Tạo đối tác thành công',
    updateSuccess: 'Cập nhật thành công',
    statusUpdate: 'Đã cập nhật trạng thái {{count}} đối tác',
    deleteSuccess: 'Đã xóa thành công {{count}} đối tác',
  },
  service: {
    duplicateCode: 'Mã đối tác đã tồn tại',
    notFound: 'Không tìm thấy đối tác',
    createFetchFailed: 'Tạo thành công nhưng không tải lại được bản ghi',
  },
  tabLabel: 'Danh sách',
} as const;

export const partner = {
  tabCategory: 'Nhóm',
  tabList: 'Danh sách',
} as const;
