/** Chữ giao diện dùng chung (nav, trang, lỗi, …) */
export const ui = {
  "nav": {
    "changePassword": {
      "title": "Đổi mật khẩu",
      "description": "Nhập mật khẩu hiện tại và mật khẩu mới để bảo mật tài khoản.",
      "currentPassword": "Mật khẩu hiện tại",
      "newPassword": "Mật khẩu mới",
      "confirmPassword": "Xác nhận mật khẩu mới",
      "showPassword": "Hiện mật khẩu",
      "hidePassword": "Ẩn mật khẩu",
      "newPasswordHint": "Ít nhất 6 ký tự.",
      "submit": "Cập nhật mật khẩu",
      "success": "Đổi mật khẩu thành công.",
      "errorCurrentRequired": "Vui lòng nhập mật khẩu hiện tại.",
      "errorNewMin": "Mật khẩu mới phải có ít nhất 6 ký tự.",
      "errorConfirmMismatch": "Xác nhận mật khẩu không khớp.",
      "errorWrongCurrent": "Mật khẩu hiện tại không đúng.",
      "errorSession": "Phiên đăng nhập không hợp lệ. Vui lòng đăng nhập lại.",
      "errorNotConfigured": "Chưa cấu hình xác thực. Liên hệ quản trị viên.",
      "errorGeneric": "Không thể đổi mật khẩu. Vui lòng thử lại."
    },
    "home": "Trang chủ",
    "back": "Quay lại",
    "licenseInfo": "Thông tin bản quyền",
    "system": "Hệ thống",
    "business": "Kinh doanh",
    "production": "Sản xuất",
    "finance": "Tài chính",
    "skipToMain": "Chuyển đến nội dung chính",
    "collapseSidebar": "Thu gọn sidebar",
    "expandSidebar": "Mở rộng sidebar",
    "closeOverlay": "Đóng overlay",
    "notification": "Thông báo",
    "userMenu": "Menu người dùng",
    "guestUser": "Khách",
    "roleAdmin": "Quản trị viên",
    "roleMember": "Thành viên",
    "userAvatarAlt": "Ảnh đại diện",
    "profile": "Hồ sơ cá nhân",
    "settings": "Cài đặt",
    "logout": "Đăng xuất",
    "logoutConfirmTitle": "Xác nhận đăng xuất",
    "logoutConfirmMessage": "Bạn có chắc chắn muốn kết thúc phiên làm việc?",
    "logoutCancel": "Hủy bỏ",
    "defaultAppDescription": "Hệ thống nền tảng số",
    "mainNav": "Điều hướng chính",
    "changePasswordLabel": "Đổi mật khẩu",
    "commandPalette": {
      "title": "Điều hướng nhanh",
      "placeholder": "Tìm trang hoặc đường dẫn…",
      "empty": "Không có kết quả",
      "hint": "Esc đóng · Enter mở · ↑↓ chọn",
      "groupGeneral": "Chung",
      "groupSystem": "Hệ thống",
      "groupBusiness": "Kinh doanh",
      "groupProduction": "Sản xuất",
      "groupFinance": "Tài chính",
      "groupAccount": "Tài khoản",
    }
  },
  "shared": {
    "export": {
      "title": "Xuất dữ liệu",
      "format": "Định dạng",
      "scope": "Phạm vi",
      "scopeAll": "Tất cả",
      "scopeCurrentPage": "Trang hiện tại",
      "scopeSelected": "Đã chọn",
      "rows": "dòng",
      "selectColumns": "Chọn cột xuất",
      "deselectAll": "Bỏ chọn hết",
      "selectAll": "Chọn tất cả",
      "pdfHeader": "Xuất ngày: {{date}} | {{count}} bản ghi",
      "exporting": "Đang xuất...",
      "exportRows": "Xuất {{count}} dòng",
      "formatXlsx": "Excel",
      "formatCsv": "CSV",
      "formatPdf": "PDF",
      "sheetName": "Du_lieu"
    },
    "import": {
      "title": "Nhập dữ liệu",
      "subtitle": "Tải lên file Excel hoặc CSV",
      "dropHere": "Kéo thả file vào đây",
      "orClickToSelect": "hoặc nhấn để chọn file (.xlsx, .xls, .csv)",
      "downloadTemplate": "Tải file mẫu (.xlsx)",
      "rowsRead": "Đã đọc {{count}} dòng dữ liệu",
      "systemColumn": "Cột hệ thống",
      "fileColumn": "Cột trong file",
      "skipColumn": "-- Bỏ qua --",
      "preview": "Xem trước (5 dòng đầu)",
      "success": "Import thành công!",
      "successCount": "{{count}} bản ghi đã được nhập",
      "error": "Không import được",
      "noDataOrHeader": "File không có dữ liệu hoặc thiếu header",
      "cannotReadFile": "Không thể đọc file. Vui lòng kiểm tra định dạng.",
      "missingRequiredColumns": "Chưa mapping cột bắt buộc: {{columns}}",
      "rowEmptyField": "Dòng {{row}}: \"{{column}}\" không được để trống",
      "importError": "Lỗi khi import dữ liệu",
      "importRows": "Nhập {{count}} dòng"
    },
    "empty": {
      "title": "Không có dữ liệu",
      "description": "Chưa có dữ liệu. Thử thêm bản ghi hoặc điều chỉnh bộ lọc."
    },
    "error": {
      "title": "Đã xảy ra lỗi",
      "message": "Không thể tải dữ liệu. Vui lòng thử lại.",
      "retry": "Tải lại",
      "backHome": "Về trang chủ",
      "reloading": "Đang tải lại...",
      "network": "Lỗi kết nối mạng. Kiểm tra internet và thử lại.",
      "unauthorized": "Phiên đăng nhập hết hạn hoặc không có quyền truy cập.",
      "forbidden": "Bạn không có quyền thực hiện thao tác này.",
      "notFound": "Không tìm thấy tài nguyên.",
      "server": "Lỗi máy chủ. Vui lòng thử lại sau.",
      "timeout": "Hết thời gian chờ. Vui lòng thử lại.",
      "unknown": "Đã xảy ra lỗi không xác định. Vui lòng thử lại.",
      "beforeInitialization": "Lỗi khởi tạo: không thể truy cập trước khi khởi tạo. Vui lòng tải lại trang.",
      "notDefined": "Tham chiếu lỗi: thành phần chưa được định nghĩa. Vui lòng tải lại trang.",
      "notFunction": "Lỗi gọi hàm: giá trị không phải là hàm. Vui lòng tải lại trang.",
      "chunkLoad": "Không tải được phần mềm. Vui lòng tải lại trang.",
      "devDetail": "Chi tiết kỹ thuật (chế độ phát triển):"
    },
    "mobileFilter": {
      "title": "Bộ lọc",
      "searchPlaceholder": "Tìm {{label}}...",
      "selectAll": "Chọn tất cả",
      "notFound": "Không tìm thấy",
      "clear": "Xóa bộ lọc"
    },
    "mobileActions": {
      "title": "Thao tác"
    }
  },
  "page": {
    "home": {
      "greeting": "Xin chào,",
      "greetingMorning": "Chào buổi sáng",
      "greetingAfternoon": "Chào buổi chiều",
      "greetingEvening": "Chào buổi tối",
      "adminFallback": "Quản trị viên",
      "systemModuleDesc": "Cấu hình, phân quyền và nhân sự.",
      "licenseInfoDesc": "Quản lý sở hữu trí tuệ và thông tin nhà phát triển.",
      "placeholderModuleDesc": "Nội dung đang được cập nhật.",
    },
    "license": {
      "title": "Thông tin Bản quyền",
      "subtitle": "Quản lý sở hữu trí tuệ và thông tin nhà phát triển",
      "unitTitle": "Đơn vị xây dựng & Phát triển",
      "companyName": "Tên công ty / Tổ chức",
      "representative": "Người đại diện",
      "taxCode": "Mã số thuế",
      "address": "Địa chỉ trụ sở",
      "rightsTitle": "Quyền hạn & Bảo mật",
      "rightsIntro": "Phần mềm này cùng toàn bộ mã nguồn, giao diện và cơ sở dữ liệu thuộc quyền sở hữu trí tuệ duy nhất của Công ty ABC. Mọi hành vi sao chép, chỉnh sửa hoặc phân phối lại mà không có sự đồng ý bằng văn bản đều là vi phạm pháp luật.",
      "version": "Phiên bản hiện tại",
      "licenseDate": "Ngày cấp phép",
      "status": "Trạng thái",
      "statusRegistered": "Đã đăng ký bản quyền tại Cục Sở hữu trí tuệ.",
      "communityLinks": "Liên kết cộng đồng",
      "website": "Website chính thức",
      "fanpage": "Fanpage Facebook",
      "communityGroup": "Group Cộng đồng",
      "zaloGroup": "Cộng đồng Zalo",
      "tiktok": "Kênh TikTok",
      "supportTitle": "Hỗ trợ kỹ thuật?",
      "supportDesc": "Gặp sự cố hoặc cần tư vấn thêm về giải pháp?",
      "contactHotline": "Liên hệ Hotline",
      "footer": "© 2024 - 2026 Bản quyền thuộc về Công ty ABC. Được bảo vệ bởi hệ thống bảo vệ bản quyền số quốc tế.",
      "technicalContact": "Liên hệ Kỹ thuật",
      "businessContact": "Liên hệ Kinh doanh",
      "contactName": "Tên",
      "contactPosition": "Chức vụ",
      "contactPhone": "Số điện thoại",
      "contactEmail": "Email"
    },
    "placeholder": {
      "backToHome": "Quay lại trang chủ",
      "backToSubmenu": "Quay lại",
      "moduleComingSoon": "Chức năng đang được phát triển.",
      "title": "Module đang được phát triển",
      "description": "Chúng tôi đang nỗ lực hoàn thiện tính năng này để mang lại trải nghiệm tốt nhất cho bạn. Vui lòng quay lại sau!",
      "descriptionWithModule": "Tính năng {{name}} đang được hoàn thiện. Vui lòng quay lại sau!",
      "badgeComingSoon": "Sắp ra mắt",
      "refreshPage": "Làm mới trang",
      "expectedCompletion": "Dự kiến hoàn thành: Quý 2 - 2026",
      "exampleDoc": "Công văn",
      "exampleContract": "Hợp đồng",
      "exampleRecruit": "Tuyển dụng",
      "exampleAttendance": "Chấm công",
      "exampleCampaign": "Chiến dịch",
      "exampleAccounting": "Kế toán",
      "exampleOrder": "Đặt hàng",
      "exampleInventory": "Tồn kho"
    },
    "login": {
      "emailRequired": "Vui lòng nhập email",
      "emailInvalid": "Email không hợp lệ",
      "usernameRequired": "Vui lòng nhập tên tài khoản",
      "usernameMin": "Tên tài khoản phải có ít nhất 2 ký tự",
      "username": "Tên tài khoản",
      "usernamePlaceholder": "VD: admin",
      "passwordMin": "Mật khẩu phải có ít nhất 6 ký tự",
      "loginSuccess": "Đăng nhập thành công!",
      "googleUser": "Google User",
      "googleSuccess": "Đăng nhập bằng Google thành công!",
      "heading": "Quản lý doanh nghiệp",
      "headingHighlight": "thông minh & hiệu quả",
      "description": "Nền tảng tích hợp AI giúp tối ưu hóa quy trình nhân sự, tài chính và vận hành hệ thống của bạn trong một giao diện duy nhất.",
      "feature1": "Tích hợp AI Assistant mạnh mẽ",
      "feature2": "Dashboard phân tích dữ liệu Realtime",
      "feature3": "Bảo mật dữ liệu tiêu chuẩn Enterprise",
      "welcome": "Chào mừng trở lại",
      "welcomeDesc": "Nhập tên tài khoản và mật khẩu để truy cập.",
      "email": "Email",
      "emailPlaceholder": "name@company.com",
      "password": "Mật khẩu",
      "showPassword": "Hiện mật khẩu",
      "hidePassword": "Ẩn mật khẩu",
      "forgotPassword": "Quên mật khẩu?",
      "rememberMe": "Ghi nhớ đăng nhập",
      "loginButton": "Đăng nhập",
      "orLoginWith": "Hoặc đăng nhập bằng",
      "forgotAccountLabel": "Tên tài khoản",
      "forgotAccountPlaceholder": "Nhập tên tài khoản đã đăng ký",
      "copyright": "© 2024",
      "companyFallback": "Mangiico ERP",
      "legal": "Bảo mật • Điều khoản sử dụng",
      "forgotPasswordTitle": "Quên mật khẩu",
      "forgotPasswordDesc": "Nhập tên tài khoản đã đăng ký, chúng tôi sẽ gửi hướng dẫn khôi phục mật khẩu.",
      "sendRecovery": "Gửi link khôi phục",
      "recoverySent": "Đã gửi thông tin khôi phục về email của bạn. Vui lòng kiểm tra hộp thư.",
      "recoverySentTitle": "Đã gửi"
    },
    "profile": {
      "nameMin": "Tên phải có ít nhất 2 ký tự",
      "emailInvalid": "Địa chỉ email không hợp lệ",
      "bioMax": "Giới thiệu không được quá 160 ký tự",
      "defaultBio": "Lập trình viên Frontend | Đam mê công nghệ",
      "updateSuccess": "Cập nhật hồ sơ thành công!",
      "userNotFound": "Không tìm thấy thông tin người dùng.",
      "title": "Hồ sơ cá nhân",
      "description": "Quản lý thông tin tài khoản và cài đặt của bạn.",
      "activeStatus": "Đang hoạt động",
      "roleUser": "User",
      "joinedAt": "Tham gia",
      "verified": "Tài khoản xác thực",
      "avatarAlt": "Avatar của {{name}}",
      "avatarAltFallback": "Avatar người dùng",
      "basicInfo": "Thông tin cơ bản",
      "fullName": "Họ và tên",
      "namePlaceholder": "Nhập tên của bạn",
      "email": "Email",
      "emailPlaceholder": "email@example.com",
      "bio": "Giới thiệu",
      "bioPlaceholder": "Mô tả ngắn về bản thân...",
      "bioHint": "Tối đa 160 ký tự",
      "settingsSection": "Cài đặt",
      "emailNotification": "Thông báo qua Email",
      "emailNotificationDesc": "Nhận cập nhật về hoạt động tài khoản và tin tức mới nhất.",
      "viewOnlyBanner": "Bạn chỉ có quyền xem hồ sơ.",
      "changeAvatar": "Đổi ảnh đại diện",
      "changePassword": "Đổi mật khẩu",
      "changePasswordTitle": "Đổi mật khẩu",
      "changePasswordDesc": "Nhập mật khẩu hiện tại và mật khẩu mới.",
      "currentPassword": "Mật khẩu hiện tại",
      "newPassword": "Mật khẩu mới",
      "confirmPassword": "Xác nhận mật khẩu mới",
      "passwordPlaceholder": "••••••••",
      "avatarModalTitle": "Đổi ảnh đại diện",
      "avatarModalHint": "Kéo thả hoặc chọn ảnh. PNG, JPG, tối đa 2MB.",
      "emptyField": "Chưa cập nhật",
      "detailSectionsTitle": "Thông tin chi tiết",
      "comingSoon": "Sắp ra mắt",
      "comingSoonDesc": "Tính năng đang được phát triển.",
      "avatarUpdateSuccess": "Đã cập nhật ảnh đại diện."
    },
    "settings": {
      "title": "Cài đặt",
      "description": "Tùy chỉnh giao diện và màu chủ đạo của ứng dụng.",
      "autoSaved": "Đã lưu tự động",
      "region": "Múi giờ & vùng",
      "timezone": "Múi giờ",
      "notifications": "Thông báo",
      "restored": "Đã khôi phục cài đặt mặc định",
      "fontSizePreview": "Văn bản mẫu — cỡ chữ áp dụng trên toàn ứng dụng."
    },
    "systemDashboard": {
      "orgChartGroup": "Sơ đồ",
      "employee": "Nhân viên",
      "employeeDesc": "Hồ sơ và thông tin nhân sự.",
      "department": "Phòng ban",
      "departmentDesc": "Cơ cấu tổ chức đơn vị.",
      "position": "Chức vụ",
      "positionDesc": "Quản lý các vị trí công việc.",
      "securityGroup": "Bảo mật & Cấu hình",
      "companyInfo": "Thông tin tổ chức",
      "companyInfoDesc": "Logo, tên ứng dụng Mangiico ERP và thông tin liên hệ hiển thị trên hệ thống.",
      "branch": "Chi nhánh",
      "branchDesc": "Khai báo các đơn vị / điểm làm việc.",
      "permission": "Phân quyền",
      "permissionDesc": "Vai trò và quyền hạn.",
      "backToSystem": "Quay lại Hệ thống"
    },
    "financeDashboard": {
      "incomeExpenseGroup": "Thu chi",
      "reportsGroup": "Báo cáo",
      "ledger": "Sổ thu chi",
      "ledgerDesc": "Ghi nhận và theo dõi các khoản thu chi.",
      "account": "Tài khoản",
      "accountDesc": "Quản lý tài khoản tiền và ngân hàng.",
      "category": "Danh mục tài chính",
      "categoryDesc": "Phân loại khoản thu, chi và tài chính.",
      "accountLookup": "Tra cứu tài khoản",
      "accountLookupDesc": "Tra cứu số dư và lịch sử theo tài khoản.",
      "financialReport": "Báo cáo tài chính",
      "financialReportDesc": "Báo cáo tổng hợp và phân tích tài chính.",
      "backToFinance": "Quay lại Tài chính"
    },
    "productionDashboard": {
      "productionGroup": "Sản xuất",
      "warehouseGroup": "Kho",
      "goodsGroup": "Hàng hóa",
      "materialsGroup": "Nguyên liệu",
      "measurementSpecGroup": "Thông số đo",
      "productionOrder": "Lệnh sản xuất",
      "productionOrderDesc": "Lập và theo dõi lệnh sản xuất.",
      "productionReport": "Báo cáo sản xuất",
      "productionReportDesc": "Báo cáo tiến độ và kết quả sản xuất.",
      "warehouseSlip": "Phiếu kho",
      "warehouseSlipDesc": "Nhập, xuất và điều chuyển kho.",
      "warehouseReport": "Báo cáo kho",
      "warehouseReportDesc": "Tồn kho và biến động kho.",
      "productCategory": "Danh mục hàng hóa",
      "productCategoryDesc": "Phân loại nhóm hàng hóa.",
      "productList": "Danh sách hàng hóa",
      "productListDesc": "Quản lý mã hàng, đơn vị và thông tin hàng.",
      "productAttributes": "Thuộc tính hàng hóa",
      "productAttributesDesc": "Khai báo thuộc tính mở rộng cho hàng hóa.",
      "measurementSpec": "Thông số đo",
      "measurementSpecDesc": "Khai báo thông số đo lường cho hàng hóa.",
      "warehouseList": "Danh sách kho",
      "warehouseListDesc": "Khai báo và quản lý các kho / vị trí lưu trữ.",
      "materialCategory": "Danh mục nguyên liệu",
      "materialCategoryDesc": "Phân loại nhóm nguyên liệu.",
      "materialList": "Danh sách nguyên liệu",
      "materialListDesc": "Quản lý mã và thông tin nguyên liệu.",
      "bom": "BOM",
      "bomDesc": "Định mức nguyên vật liệu (Bill of Materials).",
      "backToProduction": "Quay lại Sản xuất"
    }
  },
  "notification": {
    "title": "Thông báo",
    "markAllRead": "Đánh dấu tất cả đã đọc",
    "clearAll": "Xóa tất cả",
    "empty": "Chưa có thông báo",
    "emptyHint": "Các thông báo mới sẽ hiển thị tại đây.",
    "remove": "Xóa thông báo",
    "viewAll": "Xem tất cả thông báo",
    "collapse": "Thu gọn",
    "demoTooltip": "Thông báo · Tính năng đang phát triển",
    "demoBannerTitle": "Tính năng đang phát triển",
    "demoBannerDesc": "Hệ thống thông báo thời gian thực đang được hoàn thiện. Vui lòng quay lại sau."
  },
  "breadcrumb": {
    "label": "Đường dẫn",
    "home": "Trang chủ",
    "licenseInfo": "Thông tin bản quyền",
    "goHome": "Về trang chủ",
    "systemAdmin": "Hệ thống",
    "business": "Kinh doanh",
    "production": "Sản xuất",
    "finance": "Tài chính",
    "financeLedger": "Sổ thu chi",
    "financeAccount": "Tài khoản",
    "financeCategory": "Danh mục tài chính",
    "financeAccountLookup": "Tra cứu tài khoản",
    "financeReport": "Báo cáo tài chính",
    "productionOrder": "Lệnh sản xuất",
    "productionReport": "Báo cáo sản xuất",
    "warehouseSlip": "Phiếu kho",
    "warehouseReport": "Báo cáo kho",
    "productCategory": "Danh mục hàng hóa",
    "productList": "Danh sách hàng hóa",
    "productAttributes": "Thuộc tính hàng hóa",
    "measurementSpec": "Thông số đo",
    "warehouseList": "Danh sách kho",
    "materialCategory": "Danh mục nguyên liệu",
    "materialList": "Danh sách nguyên liệu",
    "bom": "BOM",
    "employee": "Nhân sự",
    "department": "Phòng ban",
    "position": "Chức vụ",
    "companyInfo": "Thông tin tổ chức",
    "branch": "Chi nhánh",
    "permission": "Phân quyền",
    "profile": "Hồ sơ cá nhân",
    "settings": "Cài đặt",
    "matTranSalarySetup": "Thiết lập lương"
  },
  "clock": {
    "sunday": "Chủ nhật",
    "monday": "Thứ 2",
    "tuesday": "Thứ 3",
    "wednesday": "Thứ 4",
    "thursday": "Thứ 5",
    "friday": "Thứ 6",
    "saturday": "Thứ 7"
  },
  "common": {
    "save": "Lưu",
    "required": "Trường bắt buộc",
    "saving": "Đang lưu...",
    "cancel": "Hủy",
    "close": "Đóng",
    "create": "Thêm",
    "view": "Xem",
    "edit": "Sửa",
    "delete": "Xóa",
    "add": "Thêm",
    "confirm": "Xác nhận",
    "deleteAll": "Xóa tất cả",
    "deleteManyConfirm": "Xóa {{count}} bản ghi đã chọn?",
    "statusChangeManyConfirm": "Đổi trạng thái {{count}} bản ghi sang {{status}}?",
    "back": "Quay lại",
    "search": "Tìm kiếm...",
    /** Menu sort trên header cột (GenericTable) — dùng chung mọi module */
    "sortAsc": "Sắp xếp A đến Z",
    "sortDesc": "Sắp xếp Z đến A",
    /** Placeholder ô tìm trong header cột (dropdown + inline) — dùng chung mọi module */
    "columnHeaderSearchPlaceholder": "Lọc…",
    "searchPlaceholder": "Tìm kiếm...",
    "searchShortcut": "Tìm kiếm... (nhấn /)",
    "unknown": "Không xác định",
    /** Giá trị trống trong bảng / chi tiết (phòng ban, chức vụ chưa gán) */
    "emptyCell": "Chưa có",
    "noData": "Không có dữ liệu",
    "noResults": "Không có kết quả phù hợp.",
    "loading": "Đang tải...",
    "active": "Hoạt động",
    "inactive": "Ngừng hoạt động",
    "status": "Trạng thái",
    "actions": "Thao tác",
    "moreRowActions": "Thao tác thêm",
    "description": "Mô tả",
    "all": "Tất cả",
    "perPage": "/ trang",
    "apply": "Áp dụng",
    "reset": "Khôi phục mặc định",
    "import": "Nhập",
    "export": "Xuất",
    /** Nút xuất vô hiệu khi ma trận không cấp quyền xuất module */
    "exportNoPermission": "Bạn không có quyền xuất dữ liệu. Liên hệ quản trị để được cấp quyền Xuất trên module tương ứng.",
    "printPreview": {
      "download": "Tải xuống",
      "downloadPdf": "PDF",
      "downloadDocx": "Word",
      "downloadXlsx": "Excel",
      "print": "In"
    },
    "addNew": "Thêm",
    "activate": "Kích hoạt",
    "deactivate": "Tắt",
    "selected": "đã chọn",
    "selectAll": "Chọn tất cả",
    "select": "Chọn",
    "deselectAll": "Bỏ chọn tất cả",
    "clearSelection": "Xóa chọn",
    "clearFilter": "Xóa bộ lọc",
    "clearFilters": "Xóa {{count}} bộ lọc",
    "moreFilters": "Thêm bộ lọc",
    "columnDisplay": "Cột hiển thị",
    "columnOptions": "Tùy chọn cột",
    "saveChanges": "Lưu",
    "cancelAction": "Hủy",
    "loadingData": "Đang tải dữ liệu",
    "processing": "Đang xử lý...",
    "finish": "Hoàn tất",
    "selectFile": "Chọn file khác",
    "allStatuses": "Tất cả trạng thái",
    "activeStatus": "Đang hoạt động",
    "inactiveStatus": "Ngừng hoạt động",
    "noDescription": "Không có mô tả",
    "error": "Đã xảy ra lỗi",
    "errorLoadData": "Không thể tải dữ liệu. Vui lòng thử lại.",
    "retry": "Thử lại",
    "firstPage": "Trang đầu",
    "prevPage": "Trang trước",
    "nextPage": "Trang sau",
    "lastPage": "Trang cuối",
    "doubleClickToPage": "Nhấn đúp để nhập trang"
  },
  "stats": {
    "columnLabel": "Tiêu đề",
    "columnValue": "Giá trị",
    "noData": "Không có dữ liệu",
    "trendVsLastPeriod": "So với kỳ trước"
  },
  "guide": {
    "buttonTitle": "Hướng dẫn",
    "modules": {},
  },
  "notFound": {
    "title": "Không tìm thấy trang",
    "message": "Đường dẫn bạn truy cập không tồn tại hoặc đã được di chuyển.",
    "backHome": "Về trang chủ"
  },
  "settings": {
    "appearance": "Giao diện",
    "displayMode": "Chế độ hiển thị",
    "primaryColor": "Màu chủ đạo",
    "colorScheme": "Giao diện",
    "colorSchemeLight": "Sáng",
    "colorSchemeDark": "Tối",
    "colorSchemeSystem": "Theo hệ thống",
    "fontFamily": "Phông chữ",
    "fontSize": "Cỡ chữ",
    "fontSizeSmall": "Nhỏ",
    "fontSizeMedium": "Vừa",
    "fontSizeLarge": "Lớn",
    "fontInter": "Inter",
    "fontBeVietnamPro": "Be Vietnam Pro",
    "fontLexend": "Lexend",
    "fontNunito": "Nunito",
    "fontSourceSans3": "Source Sans 3",
    "fontMerriweather": "Merriweather",
    "colorBlue": "Xanh dương",
    "colorViolet": "Tím",
    "colorEmerald": "Xanh lá",
    "colorRose": "Hồng",
    "colorAmber": "Cam vàng",
    "colorOrange": "Cam",
    "colorCyan": "Xanh lơ",
    "colorSlate": "Xám"
  }
} as const;
