/** Thông số đo */
export const measurementSpec = {
  noViewPermission: 'Bạn không có quyền xem module Thông số đo.',
  title: 'Thông số đo',
  deleteTitle: 'Xóa thông số đo',
  deleteMessage: 'Bạn có chắc chắn muốn xóa thông số đo này không?',
  bulkDeleteTitle: 'Xóa nhiều thông số đo',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} thông số đo đã chọn?',
  statusChangeTitle: 'Chuyển trạng thái thông số đo',
  statusChangeMessage: 'Bạn có muốn chuyển trạng thái {{count}} thông số đo sang',
  noExportData: 'Không có dữ liệu để xuất',
  exportDisplayName: 'Tên hiển thị',
  exportUnit: 'Đơn vị đo',
  exportStatus: 'Trạng thái',
  importTemplateName: 'Mau_Import_Thong_So_Do',
  active: 'Hoạt động',
  inactive: 'Ngừng',
  loading: 'Đang tải danh sách thông số đo...',
  empty: 'Chưa có thông số đo nào',
  emptyHint: 'Hãy tạo thông số đo đầu tiên cho hàng hóa.',
  listLoadErrorTitle: 'Không tải được danh sách thông số đo',
  listLoadErrorHint:
    'Kiểm tra kết nối Supabase, đăng nhập (RLS) và migration sx_thong_so_do. Thử tải lại.',
  form: {
    editTitle: 'Chỉnh sửa Thông số đo',
    createTitle: 'Thêm Thông số đo mới',
    editSubtitle: 'Cập nhật thông số đo hiện có',
    createSubtitle: 'Khai báo thông số đo lường cho hàng hóa',
    generalInfo: 'Thông tin thông số đo',
    displayName: 'Tên hiển thị',
    displayNamePlaceholder: 'VD: Ngực, Eo, Dài áo',
    unit: 'Đơn vị đo',
    unitPlaceholder: 'Chọn hoặc nhập đơn vị…',
    unitCreate: 'Thêm « {{unit}} »',
    unitSearch: 'Tìm đơn vị…',
    status: 'Trạng thái',
    validationError: 'Vui lòng kiểm tra các trường bắt buộc và thử lại.',
  },
  detail: {
    title: 'Chi tiết Thông số đo',
    subtitle: 'Thông tin thông số đo lường',
    basicInfo: 'Thông tin cơ bản',
    systemInfo: 'Hệ thống',
    createdAt: 'Ngày tạo',
    updated: 'Cập nhật',
    activate: 'Kích hoạt',
    deactivate: 'Ngừng hoạt động',
  },
  store: {
    orderCol: 'TT',
    displayNameCol: 'Tên hiển thị',
    unitCol: 'Đơn vị đo',
    statusCol: 'Trạng thái',
    updatedCol: 'Cập nhật cuối',
  },
  validation: {
    displayNameRequired: 'Vui lòng nhập tên hiển thị',
    displayNameMax: 'Tên hiển thị quá dài',
    unitRequired: 'Vui lòng nhập đơn vị đo',
    unitMax: 'Đơn vị đo quá dài',
    orderMin: 'Thứ tự phải lớn hơn hoặc bằng 0',
    statusInvalid: 'Trạng thái không hợp lệ',
  },
  toast: {
    createSuccess: 'Tạo thông số đo thành công',
    updateSuccess: 'Cập nhật thành công',
    statusUpdate: 'Đã cập nhật trạng thái {{count}} bản ghi',
    deleteSuccess: 'Đã xóa thành công {{count}} thông số đo',
    importSuccess: 'Đã nhập {{count}} thông số đo',
  },
  service: {
    duplicateName: 'Tên hiển thị đã tồn tại',
    notFound: 'Không tìm thấy thông số đo',
    createFetchFailed: 'Tạo thành công nhưng không tải lại được bản ghi',
  },
};
